/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Drone_ode_complete_runtime_bspline_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_house CASADI_PREFIX(house)
#define casadi_if_else CASADI_PREFIX(if_else)
#define casadi_norm_2 CASADI_PREFIX(norm_2)
#define casadi_qr CASADI_PREFIX(qr)
#define casadi_qr_colcomb CASADI_PREFIX(qr_colcomb)
#define casadi_qr_mv CASADI_PREFIX(qr_mv)
#define casadi_qr_singular CASADI_PREFIX(qr_singular)
#define casadi_qr_solve CASADI_PREFIX(qr_solve)
#define casadi_qr_trs CASADI_PREFIX(qr_trs)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_scal CASADI_PREFIX(scal)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_norm_2(casadi_int n, const casadi_real* x) {
  return sqrt(casadi_dot(n, x, x));
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_if_else(casadi_real c, casadi_real x, casadi_real y) { return c!=0 ? x : y;}

void casadi_scal(casadi_int n, casadi_real alpha, casadi_real* x) {
  casadi_int i;
  if (!x) return;
  for (i=0; i<n; ++i) *x++ *= alpha;
}

casadi_real casadi_house(casadi_real* v, casadi_real* beta, casadi_int nv) {
  casadi_int i;
  casadi_real v0, sigma, s, sigma_is_zero, v0_nonpos;
  v0 = v[0];
  sigma=0;
  for (i=1; i<nv; ++i) sigma += v[i]*v[i];
  s = sqrt(v0*v0 + sigma);
  sigma_is_zero = sigma==0;
  v0_nonpos = v0<=0;
  v[0] = casadi_if_else(sigma_is_zero, 1,
                 casadi_if_else(v0_nonpos, v0-s, -sigma/(v0+s)));
  *beta = casadi_if_else(sigma_is_zero, 2*v0_nonpos, -1/(s*v[0]));
  return s;
}
void casadi_qr(const casadi_int* sp_a, const casadi_real* nz_a, casadi_real* x,
               const casadi_int* sp_v, casadi_real* nz_v, const casadi_int* sp_r, casadi_real* nz_r, casadi_real* beta,
               const casadi_int* prinv, const casadi_int* pc) {
   casadi_int ncol, nrow, r, c, k, k1;
   casadi_real alpha;
   const casadi_int *a_colind, *a_row, *v_colind, *v_row, *r_colind, *r_row;
   ncol = sp_a[1];
   a_colind=sp_a+2; a_row=sp_a+2+ncol+1;
   nrow = sp_v[0];
   v_colind=sp_v+2; v_row=sp_v+2+ncol+1;
   r_colind=sp_r+2; r_row=sp_r+2+ncol+1;
   for (r=0; r<nrow; ++r) x[r] = 0;
   for (c=0; c<ncol; ++c) {
     for (k=a_colind[pc[c]]; k<a_colind[pc[c]+1]; ++k) x[prinv[a_row[k]]] = nz_a[k];
     for (k=r_colind[c]; k<r_colind[c+1] && (r=r_row[k])<c; ++k) {
       alpha = 0;
       for (k1=v_colind[r]; k1<v_colind[r+1]; ++k1) alpha += nz_v[k1]*x[v_row[k1]];
       alpha *= beta[r];
       for (k1=v_colind[r]; k1<v_colind[r+1]; ++k1) x[v_row[k1]] -= alpha*nz_v[k1];
       *nz_r++ = x[r];
       x[r] = 0;
     }
     for (k=v_colind[c]; k<v_colind[c+1]; ++k) {
       nz_v[k] = x[v_row[k]];
       x[v_row[k]] = 0;
     }
     *nz_r++ = casadi_house(nz_v + v_colind[c], beta + c, v_colind[c+1] - v_colind[c]);
   }
 }
void casadi_qr_mv(const casadi_int* sp_v, const casadi_real* v, const casadi_real* beta, casadi_real* x,
                  casadi_int tr) {
  casadi_int ncol, c, c1, k;
  casadi_real alpha;
  const casadi_int *colind, *row;
  ncol=sp_v[1];
  colind=sp_v+2; row=sp_v+2+ncol+1;
  for (c1=0; c1<ncol; ++c1) {
    c = tr ? c1 : ncol-1-c1;
    alpha=0;
    for (k=colind[c]; k<colind[c+1]; ++k) alpha += v[k]*x[row[k]];
    alpha *= beta[c];
    for (k=colind[c]; k<colind[c+1]; ++k) x[row[k]] -= alpha*v[k];
  }
}
void casadi_qr_trs(const casadi_int* sp_r, const casadi_real* nz_r, casadi_real* x, casadi_int tr) {
  casadi_int ncol, r, c, k;
  const casadi_int *colind, *row;
  ncol=sp_r[1];
  colind=sp_r+2; row=sp_r+2+ncol+1;
  if (tr) {
    for (c=0; c<ncol; ++c) {
      for (k=colind[c]; k<colind[c+1]; ++k) {
        r = row[k];
        if (r==c) {
          x[c] /= nz_r[k];
        } else {
          x[c] -= nz_r[k]*x[r];
        }
      }
    }
  } else {
    for (c=ncol-1; c>=0; --c) {
      for (k=colind[c+1]-1; k>=colind[c]; --k) {
        r=row[k];
        if (r==c) {
          x[r] /= nz_r[k];
        } else {
          x[r] -= nz_r[k]*x[c];
        }
      }
    }
  }
}
void casadi_qr_solve(casadi_real* x, casadi_int nrhs, casadi_int tr,
                     const casadi_int* sp_v, const casadi_real* v, const casadi_int* sp_r, const casadi_real* r,
                     const casadi_real* beta, const casadi_int* prinv, const casadi_int* pc, casadi_real* w) {
  casadi_int k, c, nrow_ext, ncol;
  nrow_ext = sp_v[0]; ncol = sp_v[1];
  for (k=0; k<nrhs; ++k) {
    if (tr) {
      for (c=0; c<ncol; ++c) w[c] = x[pc[c]];
      casadi_qr_trs(sp_r, r, w, 1);
      casadi_qr_mv(sp_v, v, beta, w, 0);
      for (c=0; c<ncol; ++c) x[c] = w[prinv[c]];
    } else {
      for (c=0; c<nrow_ext; ++c) w[c] = 0;
      for (c=0; c<ncol; ++c) w[prinv[c]] = x[c];
      casadi_qr_mv(sp_v, v, beta, w, 1);
      casadi_qr_trs(sp_r, r, w, 0);
      for (c=0; c<ncol; ++c) x[pc[c]] = w[c];
    }
    x += ncol;
  }
}
casadi_int casadi_qr_singular(casadi_real* rmin, casadi_int* irmin, const casadi_real* nz_r,
                             const casadi_int* sp_r, const casadi_int* pc, casadi_real eps) {
  casadi_real rd, rd_min;
  casadi_int ncol, c, nullity;
  const casadi_int* r_colind;
  nullity = 0;
  ncol = sp_r[1];
  r_colind = sp_r + 2;
  for (c=0; c<ncol; ++c) {
    rd = fabs(nz_r[r_colind[c+1]-1]);
    if (rd<eps) nullity++;
    if (c==0 || rd < rd_min) {
      rd_min = rd;
      if (rmin) *rmin = rd;
      if (irmin) *irmin = pc[c];
    }
  }
  return nullity;
}
void casadi_qr_colcomb(casadi_real* v, const casadi_real* nz_r, const casadi_int* sp_r,
                       const casadi_int* pc, casadi_real eps, casadi_int ind) {
  casadi_int ncol, r, c, k;
  const casadi_int *r_colind, *r_row;
  ncol = sp_r[1];
  r_colind = sp_r + 2;
  r_row = r_colind + ncol + 1;
  for (c=0; c<ncol; ++c) {
    if (fabs(nz_r[r_colind[c+1]-1])<eps && 0==ind--) {
      ind = c;
      break;
    }
  }
  casadi_clear(v, ncol);
  v[pc[ind]] = 1.;
  for (k=r_colind[ind]; k<r_colind[ind+1]-1; ++k) {
    v[pc[r_row[k]]] = -nz_r[k];
  }
  for (c=ind-1; c>=0; --c) {
    for (k=r_colind[c+1]-1; k>=r_colind[c]; --k) {
      r=r_row[k];
      if (r==c) {
        if (fabs(nz_r[k])<eps) {
          v[pc[r]] = 0;
        } else {
          v[pc[r]] /= nz_r[k];
        }
      } else {
        v[pc[r]] -= nz_r[k]*v[pc[c]];
      }
    }
  }
  casadi_scal(ncol, 1./sqrt(casadi_dot(ncol, v, v)), v);
}

static const casadi_int casadi_s0[3] = {0, 1, 2};
static const casadi_int casadi_s1[15] = 
  {3, 3, 0, 3, 6, 9, 0, 1,
  2, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s2[12] = 
  {3, 3, 0, 3, 5, 6, 0, 1,
  2, 1, 2, 2};
static const casadi_int casadi_s3[12] = 
  {3, 3, 0, 1, 3, 6, 0, 0,
  1, 0, 1, 2};
static const casadi_int casadi_s4[3] = {15, 1, 1};
static const casadi_int casadi_s5[3] = {5, 1, 1};
static const casadi_int casadi_s6[3] = {18, 1, 1};
static const casadi_int casadi_s7[20] = 
  {20, 1, 0, 16, 3, 4, 5, 6,
  7, 8, 9, 10, 11, 12, 14, 15,
  16, 17, 18, 19};

static const casadi_real casadi_c0[9] = 
  {1., 0., 0., 0., 1., 0., 0., 0.,
  1.};

static const casadi_real casadi_zeros[15] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0.};

/* Drone_ode_complete_runtime_bspline_expl_vde_adj:(i0[15],i1[15],i2[5],i3[18])->(o0[20x1,16nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, w01, w02, w03, *w04=w+21, *w05=w+24, *w06=w+28, w07, w08, w09, w10, w11;
  casadi_real w12, w13, w14, *w15=w+39, w16, w17, w18, *w19=w+51, w20, *w21=w+56, w22, w23;
  casadi_real *w24=w+62, w25, *w26=w+72, *w27=w+75, *w28=w+84, *w29=w+93, *w30=w+102, *w31=w+111, *w32=w+120, w33, w34, *w35=w+126;
  casadi_real *w36=w+129, *w37=w+132, w38, w39;
  const casadi_real *cr, *cs, *ct, *ss, *wr00, *wr04, *wr05, *wr06, *wr27;
  /* #0: @0 = input[1][0] */
  wr00 = arg[1] ? arg[1] : casadi_zeros;
  /* #1: {@1, @2, @3, @4, @5, @6, @7, @8} = vertsplit(@0) */
  w01 = wr00[0];
  w02 = wr00[1];
  w03 = wr00[2];
  wr04 = wr00+3;
  wr05 = wr00+6;
  wr06 = wr00+10;
  w07 = wr00[13];
  w08 = wr00[14];
  /* #2: output[0][0] = @1 */
  if (res[0]) res[0][0] = w01;
  /* #3: output[0][1] = @2 */
  if (res[0]) res[0][1] = w02;
  /* #4: output[0][2] = @3 */
  if (res[0]) res[0][2] = w03;
  /* #5: @3 = input[0][12] */
  w03 = arg[0] ? arg[0][12] : 0;
  /* #6: @2 = 0.5 */
  w02 = 5.0000000000000000e-01;
  /* #7: @5 = (@2*@5) */
  for (i=0, rr=w05, cs=wr05; i<4; ++i) (*rr++)  = (w02*(*cs++));
  /* #8: {@2, @1, @9, @10} = vertsplit(@5) */
  w02 = w05[0];
  w01 = w05[1];
  w09 = w05[2];
  w10 = w05[3];
  /* #9: @11 = (@3*@10) */
  w11  = (w03*w10);
  /* #10: @12 = input[0][11] */
  w12 = arg[0] ? arg[0][11] : 0;
  /* #11: @13 = (@12*@9) */
  w13  = (w12*w09);
  /* #12: @11 = (@11+@13) */
  w11 += w13;
  /* #13: @13 = input[0][10] */
  w13 = arg[0] ? arg[0][10] : 0;
  /* #14: @14 = (@13*@1) */
  w14  = (w13*w01);
  /* #15: @11 = (@11+@14) */
  w11 += w14;
  /* #16: @5 = zeros(4x1) */
  casadi_clear(w05, 4);
  /* #17: @15 = zeros(3x3) */
  casadi_clear(w15, 9);
  /* #18: @14 = input[0][6] */
  w14 = arg[0] ? arg[0][6] : 0;
  /* #19: @16 = input[0][7] */
  w16 = arg[0] ? arg[0][7] : 0;
  /* #20: @17 = input[0][8] */
  w17 = arg[0] ? arg[0][8] : 0;
  /* #21: @18 = input[0][9] */
  w18 = arg[0] ? arg[0][9] : 0;
  /* #22: @19 = vertcat(@14, @16, @17, @18) */
  rr=w19;
  *rr++ = w14;
  *rr++ = w16;
  *rr++ = w17;
  *rr++ = w18;
  /* #23: @20 = ||@19||_F */
  w20 = casadi_norm_2(4, w19);
  /* #24: @21 = (@19/@20) */
  for (i=0, rr=w21, cr=w19; i<4; ++i) (*rr++)  = ((*cr++)/w20);
  /* #25: @22 = @21[3] */
  for (rr=(&w22), cs=w21+3; cs!=w21+4; cs+=1) *rr++ = *cs;
  /* #26: @23 = (-@22) */
  w23 = (- w22 );
  /* #27: @24 = @15; (@24[3] = @23) */
  casadi_copy(w15, 9, w24);
  for (rr=w24+3, cs=(&w23); rr!=w24+4; rr+=1) *rr = *cs++;
  /* #28: @23 = @21[2] */
  for (rr=(&w23), cs=w21+2; cs!=w21+3; cs+=1) *rr++ = *cs;
  /* #29: (@24[6] = @23) */
  for (rr=w24+6, cs=(&w23); rr!=w24+7; rr+=1) *rr = *cs++;
  /* #30: (@24[1] = @22) */
  for (rr=w24+1, cs=(&w22); rr!=w24+2; rr+=1) *rr = *cs++;
  /* #31: @22 = @21[1] */
  for (rr=(&w22), cs=w21+1; cs!=w21+2; cs+=1) *rr++ = *cs;
  /* #32: @25 = (-@22) */
  w25 = (- w22 );
  /* #33: (@24[7] = @25) */
  for (rr=w24+7, cs=(&w25); rr!=w24+8; rr+=1) *rr = *cs++;
  /* #34: @23 = (-@23) */
  w23 = (- w23 );
  /* #35: (@24[2] = @23) */
  for (rr=w24+2, cs=(&w23); rr!=w24+3; rr+=1) *rr = *cs++;
  /* #36: (@24[5] = @22) */
  for (rr=w24+5, cs=(&w22); rr!=w24+6; rr+=1) *rr = *cs++;
  /* #37: @22 = 0.963391 */
  w22 = 9.6339113680154143e-01;
  /* #38: @4 = (@22*@4) */
  for (i=0, rr=w04, cs=wr04; i<3; ++i) (*rr++)  = (w22*(*cs++));
  /* #39: @22 = 0 */
  w22 = 0.;
  /* #40: @23 = input[2][0] */
  w23 = arg[2] ? arg[2][0] : 0;
  /* #41: @26 = vertcat(@22, @22, @23) */
  rr=w26;
  *rr++ = w22;
  *rr++ = w22;
  *rr++ = w23;
  /* #42: @26 = @26' */
  /* #43: @27 = mac(@4,@26,@15) */
  casadi_copy(w15, 9, w27);
  for (i=0, rr=w27; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w04+j, ct=w26+i*1; k<1; ++k) *rr += cs[k*3]**ct++;
  /* #44: @23 = dot(@24, @27) */
  w23 = casadi_dot(9, w24, w27);
  /* #45: @23 = (2.*@23) */
  w23 = (2.* w23 );
  /* #46: (@5[0] += @23) */
  for (rr=w05+0, cs=(&w23); rr!=w05+1; rr+=1) *rr += *cs++;
  /* #47: @23 = @21[0] */
  for (rr=(&w23), cs=w21+0; cs!=w21+1; cs+=1) *rr++ = *cs;
  /* #48: @23 = (2.*@23) */
  w23 = (2.* w23 );
  /* #49: @28 = (@23*@27) */
  for (i=0, rr=w28, cs=w27; i<9; ++i) (*rr++)  = (w23*(*cs++));
  /* #50: @29 = (2.*@24) */
  for (i=0, rr=w29, cs=w24; i<9; ++i) *rr++ = (2.* *cs++ );
  /* #51: @30 = @29' */
  for (i=0, rr=w30, cs=w29; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #52: @31 = mac(@30,@27,@15) */
  casadi_copy(w15, 9, w31);
  for (i=0, rr=w31; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w30+j, ct=w27+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #53: @28 = (@28+@31) */
  for (i=0, rr=w28, cs=w31; i<9; ++i) (*rr++) += (*cs++);
  /* #54: @31 = @24' */
  for (i=0, rr=w31, cs=w24; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #55: @30 = mac(@27,@31,@15) */
  casadi_copy(w15, 9, w30);
  for (i=0, rr=w30; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w27+j, ct=w31+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #56: @30 = (2.*@30) */
  for (i=0, rr=w30, cs=w30; i<9; ++i) *rr++ = (2.* *cs++ );
  /* #57: @28 = (@28+@30) */
  for (i=0, rr=w28, cs=w30; i<9; ++i) (*rr++) += (*cs++);
  /* #58: @25 = @28[5] */
  for (rr=(&w25), cs=w28+5; cs!=w28+6; cs+=1) *rr++ = *cs;
  /* #59: (@5[1] += @25) */
  for (rr=w05+1, cs=(&w25); rr!=w05+2; rr+=1) *rr += *cs++;
  /* #60: (@28[5] = @22) */
  for (rr=w28+5, cs=(&w22); rr!=w28+6; rr+=1) *rr = *cs++;
  /* #61: @25 = @28[2] */
  for (rr=(&w25), cs=w28+2; cs!=w28+3; cs+=1) *rr++ = *cs;
  /* #62: @25 = (-@25) */
  w25 = (- w25 );
  /* #63: (@5[2] += @25) */
  for (rr=w05+2, cs=(&w25); rr!=w05+3; rr+=1) *rr += *cs++;
  /* #64: (@28[2] = @22) */
  for (rr=w28+2, cs=(&w22); rr!=w28+3; rr+=1) *rr = *cs++;
  /* #65: @25 = @28[7] */
  for (rr=(&w25), cs=w28+7; cs!=w28+8; cs+=1) *rr++ = *cs;
  /* #66: @25 = (-@25) */
  w25 = (- w25 );
  /* #67: (@5[1] += @25) */
  for (rr=w05+1, cs=(&w25); rr!=w05+2; rr+=1) *rr += *cs++;
  /* #68: (@28[7] = @22) */
  for (rr=w28+7, cs=(&w22); rr!=w28+8; rr+=1) *rr = *cs++;
  /* #69: @25 = @28[1] */
  for (rr=(&w25), cs=w28+1; cs!=w28+2; cs+=1) *rr++ = *cs;
  /* #70: (@5[3] += @25) */
  for (rr=w05+3, cs=(&w25); rr!=w05+4; rr+=1) *rr += *cs++;
  /* #71: (@28[1] = @22) */
  for (rr=w28+1, cs=(&w22); rr!=w28+2; rr+=1) *rr = *cs++;
  /* #72: @25 = @28[6] */
  for (rr=(&w25), cs=w28+6; cs!=w28+7; cs+=1) *rr++ = *cs;
  /* #73: (@5[2] += @25) */
  for (rr=w05+2, cs=(&w25); rr!=w05+3; rr+=1) *rr += *cs++;
  /* #74: (@28[6] = @22) */
  for (rr=w28+6, cs=(&w22); rr!=w28+7; rr+=1) *rr = *cs++;
  /* #75: @25 = @28[3] */
  for (rr=(&w25), cs=w28+3; cs!=w28+4; cs+=1) *rr++ = *cs;
  /* #76: @25 = (-@25) */
  w25 = (- w25 );
  /* #77: (@5[3] += @25) */
  for (rr=w05+3, cs=(&w25); rr!=w05+4; rr+=1) *rr += *cs++;
  /* #78: @32 = (@5/@20) */
  for (i=0, rr=w32, cr=w05; i<4; ++i) (*rr++)  = ((*cr++)/w20);
  /* #79: @21 = (@21/@20) */
  for (i=0, rr=w21; i<4; ++i) (*rr++) /= w20;
  /* #80: @21 = (-@21) */
  for (i=0, rr=w21, cs=w21; i<4; ++i) *rr++ = (- *cs++ );
  /* #81: @25 = dot(@21, @5) */
  w25 = casadi_dot(4, w21, w05);
  /* #82: @25 = (@25/@20) */
  w25 /= w20;
  /* #83: @19 = (@25*@19) */
  for (i=0, rr=w19, cs=w19; i<4; ++i) (*rr++)  = (w25*(*cs++));
  /* #84: @32 = (@32+@19) */
  for (i=0, rr=w32, cs=w19; i<4; ++i) (*rr++) += (*cs++);
  /* #85: {@25, @20, @33, @34} = vertsplit(@32) */
  w25 = w32[0];
  w20 = w32[1];
  w33 = w32[2];
  w34 = w32[3];
  /* #86: @11 = (@11+@25) */
  w11 += w25;
  /* #87: output[0][3] = @11 */
  if (res[0]) res[0][3] = w11;
  /* #88: @11 = (@12*@10) */
  w11  = (w12*w10);
  /* #89: @25 = (@3*@9) */
  w25  = (w03*w09);
  /* #90: @11 = (@11-@25) */
  w11 -= w25;
  /* #91: @25 = (@13*@2) */
  w25  = (w13*w02);
  /* #92: @11 = (@11-@25) */
  w11 -= w25;
  /* #93: @11 = (@11+@20) */
  w11 += w20;
  /* #94: output[0][4] = @11 */
  if (res[0]) res[0][4] = w11;
  /* #95: @11 = (@3*@1) */
  w11  = (w03*w01);
  /* #96: @20 = (@13*@10) */
  w20  = (w13*w10);
  /* #97: @11 = (@11-@20) */
  w11 -= w20;
  /* #98: @20 = (@12*@2) */
  w20  = (w12*w02);
  /* #99: @11 = (@11-@20) */
  w11 -= w20;
  /* #100: @11 = (@11+@33) */
  w11 += w33;
  /* #101: output[0][5] = @11 */
  if (res[0]) res[0][5] = w11;
  /* #102: @11 = (@13*@9) */
  w11  = (w13*w09);
  /* #103: @33 = (@12*@1) */
  w33  = (w12*w01);
  /* #104: @11 = (@11-@33) */
  w11 -= w33;
  /* #105: @33 = (@3*@2) */
  w33  = (w03*w02);
  /* #106: @11 = (@11-@33) */
  w11 -= w33;
  /* #107: @11 = (@11+@34) */
  w11 += w34;
  /* #108: output[0][6] = @11 */
  if (res[0]) res[0][6] = w11;
  /* #109: @26 = zeros(3x1) */
  casadi_clear(w26, 3);
  /* #110: @11 = 0.0032086 */
  w11 = 3.2085999999999998e-03;
  /* #111: @35 = horzcat(@11, @22, @22) */
  rr=w35;
  *rr++ = w11;
  *rr++ = w22;
  *rr++ = w22;
  /* #112: @35 = @35' */
  /* #113: @11 = 0.0016731 */
  w11 = 1.6731000000000001e-03;
  /* #114: @36 = horzcat(@22, @11, @22) */
  rr=w36;
  *rr++ = w22;
  *rr++ = w11;
  *rr++ = w22;
  /* #115: @36 = @36' */
  /* #116: @11 = 0.001673 */
  w11 = 1.6730000000000000e-03;
  /* #117: @37 = horzcat(@22, @22, @11) */
  rr=w37;
  *rr++ = w22;
  *rr++ = w22;
  *rr++ = w11;
  /* #118: @37 = @37' */
  /* #119: @28 = horzcat(@35, @36, @37) */
  rr=w28;
  for (i=0, cs=w35; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w36; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w37; i<3; ++i) *rr++ = *cs++;
  /* #120: @30 = @28' */
  for (i=0, rr=w30, cs=w28; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #121: @35 = vertcat(@13, @12, @3) */
  rr=w35;
  *rr++ = w13;
  *rr++ = w12;
  *rr++ = w03;
  /* #122: @36 = mac(@30,@35,@26) */
  casadi_copy(w26, 3, w36);
  for (i=0, rr=w36; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w30+j, ct=w35+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #123: @22 = @36[1] */
  for (rr=(&w22), cs=w36+1; cs!=w36+2; cs+=1) *rr++ = *cs;
  /* #124: @27 = 
  [[1, 0, 0], 
   [0, 1, 0], 
   [0, 0, 1]] */
  wr27 = casadi_c0;
  /* #125: @31 = (@30\@27) */
  rr = w31;
  ss = w30;
  casadi_copy(wr27, 9, rr);
  {
    /* FIXME(@jaeandersson): Memory allocation can be avoided */
    casadi_real v[6], r[6], beta[3], w[6];
    casadi_qr(casadi_s1, ss, w, casadi_s2, v, casadi_s3, r, beta, casadi_s0, casadi_s0);
    casadi_qr_solve(rr, 3, 0, casadi_s2, v, casadi_s3, r, beta, casadi_s0, casadi_s0, w);
  }
  /* #126: @30 = @31' */
  for (i=0, rr=w30, cs=w31; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #127: @35 = mac(@30,@6,@26) */
  casadi_copy(w26, 3, w35);
  for (i=0, rr=w35; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w30+j, ct=wr06+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #128: @6 = (-@35) */
  for (i=0, rr=w06, cs=w35; i<3; ++i) *rr++ = (- *cs++ );
  /* #129: {@11, @34, @33} = vertsplit(@6) */
  w11 = w06[0];
  w34 = w06[1];
  w33 = w06[2];
  /* #130: @20 = (@22*@33) */
  w20  = (w22*w33);
  /* #131: @25 = @36[2] */
  for (rr=(&w25), cs=w36+2; cs!=w36+3; cs+=1) *rr++ = *cs;
  /* #132: @38 = (@25*@34) */
  w38  = (w25*w34);
  /* #133: @20 = (@20-@38) */
  w20 -= w38;
  /* #134: @38 = (@3*@34) */
  w38  = (w03*w34);
  /* #135: @39 = (@12*@33) */
  w39  = (w12*w33);
  /* #136: @38 = (@38-@39) */
  w38 -= w39;
  /* #137: @6 = @26; (@6[0] += @38) */
  casadi_copy(w26, 3, w06);
  for (rr=w06+0, cs=(&w38); rr!=w06+1; rr+=1) *rr += *cs++;
  /* #138: @38 = (@13*@33) */
  w38  = (w13*w33);
  /* #139: @3 = (@3*@11) */
  w03 *= w11;
  /* #140: @38 = (@38-@3) */
  w38 -= w03;
  /* #141: (@6[1] += @38) */
  for (rr=w06+1, cs=(&w38); rr!=w06+2; rr+=1) *rr += *cs++;
  /* #142: @12 = (@12*@11) */
  w12 *= w11;
  /* #143: @13 = (@13*@34) */
  w13 *= w34;
  /* #144: @12 = (@12-@13) */
  w12 -= w13;
  /* #145: (@6[2] += @12) */
  for (rr=w06+2, cs=(&w12); rr!=w06+3; rr+=1) *rr += *cs++;
  /* #146: @37 = mac(@28,@6,@26) */
  casadi_copy(w26, 3, w37);
  for (i=0, rr=w37; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w28+j, ct=w06+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #147: {@12, @13, @38} = vertsplit(@37) */
  w12 = w37[0];
  w13 = w37[1];
  w38 = w37[2];
  /* #148: @20 = (@20+@12) */
  w20 += w12;
  /* #149: @12 = (@17*@10) */
  w12  = (w17*w10);
  /* #150: @20 = (@20-@12) */
  w20 -= w12;
  /* #151: @12 = (@18*@9) */
  w12  = (w18*w09);
  /* #152: @20 = (@20+@12) */
  w20 += w12;
  /* #153: @12 = (@14*@1) */
  w12  = (w14*w01);
  /* #154: @20 = (@20+@12) */
  w20 += w12;
  /* #155: @12 = (@16*@2) */
  w12  = (w16*w02);
  /* #156: @20 = (@20-@12) */
  w20 -= w12;
  /* #157: output[0][7] = @20 */
  if (res[0]) res[0][7] = w20;
  /* #158: @25 = (@25*@11) */
  w25 *= w11;
  /* #159: @20 = @36[0] */
  for (rr=(&w20), cs=w36+0; cs!=w36+1; cs+=1) *rr++ = *cs;
  /* #160: @33 = (@20*@33) */
  w33  = (w20*w33);
  /* #161: @25 = (@25-@33) */
  w25 -= w33;
  /* #162: @25 = (@25+@13) */
  w25 += w13;
  /* #163: @13 = (@16*@10) */
  w13  = (w16*w10);
  /* #164: @25 = (@25+@13) */
  w25 += w13;
  /* #165: @13 = (@14*@9) */
  w13  = (w14*w09);
  /* #166: @25 = (@25+@13) */
  w25 += w13;
  /* #167: @13 = (@18*@1) */
  w13  = (w18*w01);
  /* #168: @25 = (@25-@13) */
  w25 -= w13;
  /* #169: @13 = (@17*@2) */
  w13  = (w17*w02);
  /* #170: @25 = (@25-@13) */
  w25 -= w13;
  /* #171: output[0][8] = @25 */
  if (res[0]) res[0][8] = w25;
  /* #172: @20 = (@20*@34) */
  w20 *= w34;
  /* #173: @22 = (@22*@11) */
  w22 *= w11;
  /* #174: @20 = (@20-@22) */
  w20 -= w22;
  /* #175: @20 = (@20+@38) */
  w20 += w38;
  /* #176: @14 = (@14*@10) */
  w14 *= w10;
  /* #177: @20 = (@20+@14) */
  w20 += w14;
  /* #178: @16 = (@16*@9) */
  w16 *= w09;
  /* #179: @20 = (@20-@16) */
  w20 -= w16;
  /* #180: @17 = (@17*@1) */
  w17 *= w01;
  /* #181: @20 = (@20+@17) */
  w20 += w17;
  /* #182: @18 = (@18*@2) */
  w18 *= w02;
  /* #183: @20 = (@20-@18) */
  w20 -= w18;
  /* #184: output[0][9] = @20 */
  if (res[0]) res[0][9] = w20;
  /* #185: output[0][10] = @7 */
  if (res[0]) res[0][10] = w07;
  /* #186: @15 = mac(@29,@24,@15) */
  for (i=0, rr=w15; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w29+j, ct=w24+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #187: @27 = (@27+@15) */
  for (i=0, rr=w27, cr=wr27, cs=w15; i<9; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #188: @24 = (@23*@24) */
  for (i=0, rr=w24, cs=w24; i<9; ++i) (*rr++)  = (w23*(*cs++));
  /* #189: @27 = (@27+@24) */
  for (i=0, rr=w27, cs=w24; i<9; ++i) (*rr++) += (*cs++);
  /* #190: @24 = @27' */
  for (i=0, rr=w24, cs=w27; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #191: @26 = mac(@24,@4,@26) */
  for (i=0, rr=w26; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w24+j, ct=w04+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #192: {NULL, NULL, @23} = vertsplit(@26) */
  w23 = w26[2];
  /* #193: output[0][11] = @23 */
  if (res[0]) res[0][11] = w23;
  /* #194: {@23, @7, @20} = vertsplit(@35) */
  w23 = w35[0];
  w07 = w35[1];
  w20 = w35[2];
  /* #195: output[0][12] = @23 */
  if (res[0]) res[0][12] = w23;
  /* #196: output[0][13] = @7 */
  if (res[0]) res[0][13] = w07;
  /* #197: output[0][14] = @20 */
  if (res[0]) res[0][14] = w20;
  /* #198: output[0][15] = @8 */
  if (res[0]) res[0][15] = w08;
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_runtime_bspline_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_runtime_bspline_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_runtime_bspline_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_complete_runtime_bspline_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_runtime_bspline_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_complete_runtime_bspline_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_complete_runtime_bspline_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_complete_runtime_bspline_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_complete_runtime_bspline_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_complete_runtime_bspline_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real Drone_ode_complete_runtime_bspline_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_complete_runtime_bspline_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_complete_runtime_bspline_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_complete_runtime_bspline_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s4;
    case 2: return casadi_s5;
    case 3: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_complete_runtime_bspline_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s7;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_runtime_bspline_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8;
  if (sz_res) *sz_res = 9;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 137;
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_complete_runtime_bspline_expl_vde_adj_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 9*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 137*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
