/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) DQ_Drone_MPCC_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_norm_2 CASADI_PREFIX(norm_2)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_norm_2(casadi_int n, const casadi_real* x) {
  return sqrt(casadi_dot(n, x, x));
}

static const casadi_int casadi_s0[3] = {15, 1, 1};
static const casadi_int casadi_s1[3] = {5, 1, 1};
static const casadi_int casadi_s2[3] = {1, 1, 1};
static const casadi_int casadi_s3[3] = {20, 1, 1};

static const casadi_real casadi_c0[9] = 
  {3.0558700000000000e-03, 0., 0., 0., 1.5969500000000000e-03, 0., 0., 0.,
  1.5968700000000000e-03};
static const casadi_real casadi_c1[3] = {3.2723905139943781e+02, 6.2619368170575160e+02, 6.2622505275946071e+02};

static const casadi_real casadi_zeros[15] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0.};

/* DQ_Drone_MPCC_expl_vde_adj:(i0[15],i1[15],i2[5],i3)->(o0[20]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *w00=w+8, *w01=w+24, *w02=w+28, *w03=w+43, *w04=w+51, w06, *w07=w+58, *w08=w+61, w09, w10, w11;
  casadi_real w12, w13, w14, w15, w16, w17, w18, w19, w20, w21, w22, w23;
  casadi_real *w24=w+80, *w25=w+84, *w26=w+88, *w27=w+104, *w28=w+120, *w29=w+124, *w30=w+128, w31, w32, w33, *w34=w+135, *w35=w+138;
  casadi_real w36, w37, w38, w39, w40, w41, w42, w43, w44, w45, w46, w47;
  casadi_real *w48=w+154, w49, w50, w51, w52, w53, w54, w55, w56, w57, *w59=w+187, *w60=w+196;
  casadi_real *w61=w+199, w62, w63, w64, w65, w66, w67, w68, w69, w70, w71, *w72=w+212;
  casadi_real *w73=w+276, *w74=w+284, *w75=w+348, *w76=w+380, *w77=w+412, *w78=w+444, w79, w80, w81, w82, w83, w84;
  casadi_real w85, w86, w87, w88, w89, *w90=w+471;
  const casadi_real *cs, *ct, *wr01, *wr02, *wr03, *wr04, *wr05, *wr58;
  /* #0: @0 = zeros(4x4) */
  casadi_clear(w00, 16);
  /* #1: @1 = zeros(4x1) */
  casadi_clear(w01, 4);
  /* #2: @2 = input[1][0] */
  wr02 = arg[1] ? arg[1] : casadi_zeros;
  /* #3: {@3, @4, @5, @6} = vertsplit(@2) */
  wr03 = wr02;
  wr04 = wr02+8;
  wr05 = wr02+11;
  w06 = wr02[14];
  /* #4: @7 = (-@5) */
  for (i=0, rr=w07, cs=wr05; i<3; ++i) *rr++ = (- *cs++ );
  /* #5: @8 = @1; (@8[1:4] += @7) */
  casadi_copy(w01, 4, w08);
  for (rr=w08+1, cs=w07; rr!=w08+4; rr+=1) *rr += *cs++;
  /* #6: @9 = input[0][0] */
  w09 = arg[0] ? arg[0][0] : 0;
  /* #7: @10 = input[0][1] */
  w10 = arg[0] ? arg[0][1] : 0;
  /* #8: @11 = input[0][2] */
  w11 = arg[0] ? arg[0][2] : 0;
  /* #9: @12 = input[0][3] */
  w12 = arg[0] ? arg[0][3] : 0;
  /* #10: @13 = input[0][4] */
  w13 = arg[0] ? arg[0][4] : 0;
  /* #11: @14 = input[0][5] */
  w14 = arg[0] ? arg[0][5] : 0;
  /* #12: @15 = input[0][6] */
  w15 = arg[0] ? arg[0][6] : 0;
  /* #13: @16 = input[0][7] */
  w16 = arg[0] ? arg[0][7] : 0;
  /* #14: @17 = input[0][8] */
  w17 = arg[0] ? arg[0][8] : 0;
  /* #15: @18 = input[0][9] */
  w18 = arg[0] ? arg[0][9] : 0;
  /* #16: @19 = input[0][10] */
  w19 = arg[0] ? arg[0][10] : 0;
  /* #17: @20 = input[0][11] */
  w20 = arg[0] ? arg[0][11] : 0;
  /* #18: @21 = input[0][12] */
  w21 = arg[0] ? arg[0][12] : 0;
  /* #19: @22 = input[0][13] */
  w22 = arg[0] ? arg[0][13] : 0;
  /* #20: @23 = input[0][14] */
  w23 = arg[0] ? arg[0][14] : 0;
  /* #21: @2 = vertcat(@9, @10, @11, @12, @13, @14, @15, @16, @17, @18, @19, @20, @21, @22, @23) */
  rr=w02;
  *rr++ = w09;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w17;
  *rr++ = w18;
  *rr++ = w19;
  *rr++ = w20;
  *rr++ = w21;
  *rr++ = w22;
  *rr++ = w23;
  /* #22: @24 = @2[:4] */
  for (rr=w24, cs=w02+0; cs!=w02+4; cs+=1) *rr++ = *cs;
  /* #23: @25 = @24' */
  casadi_copy(w24, 4, w25);
  /* #24: @26 = mac(@8,@25,@0) */
  casadi_copy(w00, 16, w26);
  for (i=0, rr=w26; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, cs=w08+j, ct=w25+i*1; k<1; ++k) *rr += cs[k*4]**ct++;
  /* #25: @27 = @26' */
  for (i=0, rr=w27, cs=w26; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #26: {@25, @28, @29, @30} = horzsplit(@27) */
  casadi_copy(w27, 4, w25);
  casadi_copy(w27+4, 4, w28);
  casadi_copy(w27+8, 4, w29);
  casadi_copy(w27+12, 4, w30);
  /* #27: @30 = @30' */
  /* #28: {@23, @31, @32, @33} = horzsplit(@30) */
  w23 = w30[0];
  w31 = w30[1];
  w32 = w30[2];
  w33 = w30[3];
  /* #29: @30 = @1; (@30[0] += @33) */
  casadi_copy(w01, 4, w30);
  for (rr=w30+0, cs=(&w33); rr!=w30+1; rr+=1) *rr += *cs++;
  /* #30: (@30[1] += @32) */
  for (rr=w30+1, cs=(&w32); rr!=w30+2; rr+=1) *rr += *cs++;
  /* #31: @31 = (-@31) */
  w31 = (- w31 );
  /* #32: (@30[2] += @31) */
  for (rr=w30+2, cs=(&w31); rr!=w30+3; rr+=1) *rr += *cs++;
  /* #33: (@30[3] += @23) */
  for (rr=w30+3, cs=(&w23); rr!=w30+4; rr+=1) *rr += *cs++;
  /* #34: @29 = @29' */
  /* #35: {@23, @31, @32, @33} = horzsplit(@29) */
  w23 = w29[0];
  w31 = w29[1];
  w32 = w29[2];
  w33 = w29[3];
  /* #36: @33 = (-@33) */
  w33 = (- w33 );
  /* #37: (@30[1] += @33) */
  for (rr=w30+1, cs=(&w33); rr!=w30+2; rr+=1) *rr += *cs++;
  /* #38: (@30[0] += @32) */
  for (rr=w30+0, cs=(&w32); rr!=w30+1; rr+=1) *rr += *cs++;
  /* #39: (@30[3] += @31) */
  for (rr=w30+3, cs=(&w31); rr!=w30+4; rr+=1) *rr += *cs++;
  /* #40: (@30[2] += @23) */
  for (rr=w30+2, cs=(&w23); rr!=w30+3; rr+=1) *rr += *cs++;
  /* #41: @28 = @28' */
  /* #42: {@23, @31, @32, @33} = horzsplit(@28) */
  w23 = w28[0];
  w31 = w28[1];
  w32 = w28[2];
  w33 = w28[3];
  /* #43: (@30[2] += @33) */
  for (rr=w30+2, cs=(&w33); rr!=w30+3; rr+=1) *rr += *cs++;
  /* #44: @32 = (-@32) */
  w32 = (- w32 );
  /* #45: (@30[3] += @32) */
  for (rr=w30+3, cs=(&w32); rr!=w30+4; rr+=1) *rr += *cs++;
  /* #46: (@30[0] += @31) */
  for (rr=w30+0, cs=(&w31); rr!=w30+1; rr+=1) *rr += *cs++;
  /* #47: (@30[1] += @23) */
  for (rr=w30+1, cs=(&w23); rr!=w30+2; rr+=1) *rr += *cs++;
  /* #48: @25 = @25' */
  /* #49: {@23, @31, @32, @33} = horzsplit(@25) */
  w23 = w25[0];
  w31 = w25[1];
  w32 = w25[2];
  w33 = w25[3];
  /* #50: @33 = (-@33) */
  w33 = (- w33 );
  /* #51: (@30[3] += @33) */
  for (rr=w30+3, cs=(&w33); rr!=w30+4; rr+=1) *rr += *cs++;
  /* #52: @32 = (-@32) */
  w32 = (- w32 );
  /* #53: (@30[2] += @32) */
  for (rr=w30+2, cs=(&w32); rr!=w30+3; rr+=1) *rr += *cs++;
  /* #54: @31 = (-@31) */
  w31 = (- w31 );
  /* #55: (@30[1] += @31) */
  for (rr=w30+1, cs=(&w31); rr!=w30+2; rr+=1) *rr += *cs++;
  /* #56: (@30[0] += @23) */
  for (rr=w30+0, cs=(&w23); rr!=w30+1; rr+=1) *rr += *cs++;
  /* #57: @23 = 0 */
  w23 = 0.;
  /* #58: @31 = 9.81 */
  w31 = 9.8100000000000005e+00;
  /* #59: @32 = 1 */
  w32 = 1.;
  /* #60: @7 = vertcat(@23, @23, @32) */
  rr=w07;
  *rr++ = w23;
  *rr++ = w23;
  *rr++ = w32;
  /* #61: @34 = (@31*@7) */
  for (i=0, rr=w34, cs=w07; i<3; ++i) (*rr++)  = (w31*(*cs++));
  /* #62: @25 = vertcat(@23, @34) */
  rr=w25;
  *rr++ = w23;
  for (i=0, cs=w34; i<3; ++i) *rr++ = *cs++;
  /* #63: @28 = @25' */
  casadi_copy(w25, 4, w28);
  /* #64: @27 = mac(@30,@28,@0) */
  casadi_copy(w00, 16, w27);
  for (i=0, rr=w27; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, cs=w30+j, ct=w28+i*1; k<1; ++k) *rr += cs[k*4]**ct++;
  /* #65: @26 = @27' */
  for (i=0, rr=w26, cs=w27; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #66: {@30, @28, @29, @35} = horzsplit(@26) */
  casadi_copy(w26, 4, w30);
  casadi_copy(w26+4, 4, w28);
  casadi_copy(w26+8, 4, w29);
  casadi_copy(w26+12, 4, w35);
  /* #67: @35 = @35' */
  /* #68: {@31, @33, @36, @37} = horzsplit(@35) */
  w31 = w35[0];
  w33 = w35[1];
  w36 = w35[2];
  w37 = w35[3];
  /* #69: @29 = @29' */
  /* #70: {@38, @39, @40, @41} = horzsplit(@29) */
  w38 = w29[0];
  w39 = w29[1];
  w40 = w29[2];
  w41 = w29[3];
  /* #71: @37 = (@37+@40) */
  w37 += w40;
  /* #72: @28 = @28' */
  /* #73: {@40, @42, @43, @44} = horzsplit(@28) */
  w40 = w28[0];
  w42 = w28[1];
  w43 = w28[2];
  w44 = w28[3];
  /* #74: @37 = (@37+@42) */
  w37 += w42;
  /* #75: @30 = @30' */
  /* #76: {@42, @45, @46, @47} = horzsplit(@30) */
  w42 = w30[0];
  w45 = w30[1];
  w46 = w30[2];
  w47 = w30[3];
  /* #77: @37 = (@37+@42) */
  w37 += w42;
  /* #78: @48 = zeros(15x1) */
  casadi_clear(w48, 15);
  /* #79: @30 = horzcat(@9, @10, @11, @12) */
  rr=w30;
  *rr++ = w09;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  /* #80: @30 = @30' */
  /* #81: @42 = (-@10) */
  w42 = (- w10 );
  /* #82: @49 = (-@11) */
  w49 = (- w11 );
  /* #83: @28 = horzcat(@42, @9, @12, @49) */
  rr=w28;
  *rr++ = w42;
  *rr++ = w09;
  *rr++ = w12;
  *rr++ = w49;
  /* #84: @28 = @28' */
  /* #85: @50 = (-@12) */
  w50 = (- w12 );
  /* #86: @29 = horzcat(@49, @50, @9, @10) */
  rr=w29;
  *rr++ = w49;
  *rr++ = w50;
  *rr++ = w09;
  *rr++ = w10;
  /* #87: @29 = @29' */
  /* #88: @35 = horzcat(@50, @11, @42, @9) */
  rr=w35;
  *rr++ = w50;
  *rr++ = w11;
  *rr++ = w42;
  *rr++ = w09;
  /* #89: @35 = @35' */
  /* #90: @26 = horzcat(@30, @28, @29, @35) */
  rr=w26;
  for (i=0, cs=w30; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w28; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w29; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w35; i<4; ++i) *rr++ = *cs++;
  /* #91: @27 = @26' */
  for (i=0, rr=w27, cs=w26; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #92: @30 = mac(@27,@25,@1) */
  casadi_copy(w01, 4, w30);
  for (i=0, rr=w30; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, cs=w27+j, ct=w25+i*4; k<4; ++k) *rr += cs[k*4]**ct++;
  /* #93: @51 = @30[0] */
  for (rr=(&w51), cs=w30+0; cs!=w30+1; cs+=1) *rr++ = *cs;
  /* #94: @52 = @30[1] */
  for (rr=(&w52), cs=w30+1; cs!=w30+2; cs+=1) *rr++ = *cs;
  /* #95: @53 = (-@52) */
  w53 = (- w52 );
  /* #96: @54 = @30[2] */
  for (rr=(&w54), cs=w30+2; cs!=w30+3; cs+=1) *rr++ = *cs;
  /* #97: @55 = (-@54) */
  w55 = (- w54 );
  /* #98: @56 = @30[3] */
  for (rr=(&w56), cs=w30+3; cs!=w30+4; cs+=1) *rr++ = *cs;
  /* #99: @57 = (-@56) */
  w57 = (- w56 );
  /* #100: @30 = horzcat(@51, @53, @55, @57) */
  rr=w30;
  *rr++ = w51;
  *rr++ = w53;
  *rr++ = w55;
  *rr++ = w57;
  /* #101: @30 = @30' */
  /* #102: @25 = horzcat(@52, @51, @57, @54) */
  rr=w25;
  *rr++ = w52;
  *rr++ = w51;
  *rr++ = w57;
  *rr++ = w54;
  /* #103: @25 = @25' */
  /* #104: @28 = horzcat(@54, @56, @51, @53) */
  rr=w28;
  *rr++ = w54;
  *rr++ = w56;
  *rr++ = w51;
  *rr++ = w53;
  /* #105: @28 = @28' */
  /* #106: @29 = horzcat(@56, @55, @52, @51) */
  rr=w29;
  *rr++ = w56;
  *rr++ = w55;
  *rr++ = w52;
  *rr++ = w51;
  /* #107: @29 = @29' */
  /* #108: @27 = horzcat(@30, @25, @28, @29) */
  rr=w27;
  for (i=0, cs=w30; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w25; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w28; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w29; i<4; ++i) *rr++ = *cs++;
  /* #109: @1 = mac(@27,@8,@1) */
  for (i=0, rr=w01; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, cs=w27+j, ct=w08+i*4; k<4; ++k) *rr += cs[k*4]**ct++;
  /* #110: (@48[:4] += @1) */
  for (rr=w48+0, cs=w01; rr!=w48+4; rr+=1) *rr += *cs++;
  /* #111: @34 = zeros(3x1) */
  casadi_clear(w34, 3);
  /* #112: @58 = 
  [[0.00305587, 0, 0], 
   [0, 0.00159695, 0], 
   [0, 0, 0.00159687]] */
  wr58 = casadi_c0;
  /* #113: @59 = @58' */
  for (i=0, rr=w59, cs=wr58; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #114: @60 = 
  [[327.239, 00, 00], 
   [00, 626.194, 00], 
   [00, 00, 626.225]] */
  casadi_copy(casadi_c1, 3, w60);
  /* #115: @60 = nonzeros(@60) */
  /* #116: @60 = (@60*@4) */
  for (i=0, rr=w60, cs=wr04; i<3; ++i) (*rr++) *= (*cs++);
  /* #117: @4 = (-@60) */
  for (i=0, rr=w04, cs=w60; i<3; ++i) *rr++ = (- *cs++ );
  /* #118: {@56, @55, @52} = vertsplit(@4) */
  w56 = w04[0];
  w55 = w04[1];
  w52 = w04[2];
  /* #119: @51 = (@19*@55) */
  w51  = (w19*w55);
  /* #120: @54 = (@18*@52) */
  w54  = (w18*w52);
  /* #121: @51 = (@51-@54) */
  w51 -= w54;
  /* #122: @4 = @34; (@4[0] += @51) */
  casadi_copy(w34, 3, w04);
  for (rr=w04+0, cs=(&w51); rr!=w04+1; rr+=1) *rr += *cs++;
  /* #123: @51 = (@17*@52) */
  w51  = (w17*w52);
  /* #124: @54 = (@19*@56) */
  w54  = (w19*w56);
  /* #125: @51 = (@51-@54) */
  w51 -= w54;
  /* #126: (@4[1] += @51) */
  for (rr=w04+1, cs=(&w51); rr!=w04+2; rr+=1) *rr += *cs++;
  /* #127: @51 = (@18*@56) */
  w51  = (w18*w56);
  /* #128: @54 = (@17*@55) */
  w54  = (w17*w55);
  /* #129: @51 = (@51-@54) */
  w51 -= w54;
  /* #130: (@4[2] += @51) */
  for (rr=w04+2, cs=(&w51); rr!=w04+3; rr+=1) *rr += *cs++;
  /* #131: @61 = mac(@59,@4,@34) */
  casadi_copy(w34, 3, w61);
  for (i=0, rr=w61; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w59+j, ct=w04+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #132: (@48[8:11] += @61) */
  for (rr=w48+8, cs=w61; rr!=w48+11; rr+=1) *rr += *cs++;
  /* #133: @51 = 10 */
  w51 = 10.;
  /* #134: @54 = ||@24||_F */
  w54 = casadi_norm_2(4, w24);
  /* #135: @32 = (@32-@54) */
  w32 -= w54;
  /* #136: @32 = (@51*@32) */
  w32  = (w51*w32);
  /* #137: {@1, NULL} = vertsplit(@3) */
  wr01 = wr03;
  /* #138: @8 = (@32*@1) */
  for (i=0, rr=w08, cs=wr01; i<4; ++i) (*rr++)  = (w32*(*cs++));
  /* #139: @32 = dot(@24, @1) */
  w32 = casadi_dot(4, w24, wr01);
  /* #140: @51 = (@51*@32) */
  w51 *= w32;
  /* #141: @51 = (@51/@54) */
  w51 /= w54;
  /* #142: @24 = (@51*@24) */
  for (i=0, rr=w24, cs=w24; i<4; ++i) (*rr++)  = (w51*(*cs++));
  /* #143: @8 = (@8-@24) */
  for (i=0, rr=w08, cs=w24; i<4; ++i) (*rr++) -= (*cs++);
  /* #144: (@48[:4] += @8) */
  for (rr=w48+0, cs=w08; rr!=w48+4; rr+=1) *rr += *cs++;
  /* #145: {@51, @54, @32, @53, @57, @62, @63, @64, @65, @66, @67, @68, @69, @70, @71} = vertsplit(@48) */
  w51 = w48[0];
  w54 = w48[1];
  w32 = w48[2];
  w53 = w48[3];
  w57 = w48[4];
  w62 = w48[5];
  w63 = w48[6];
  w64 = w48[7];
  w65 = w48[8];
  w66 = w48[9];
  w67 = w48[10];
  w68 = w48[11];
  w69 = w48[12];
  w70 = w48[13];
  w71 = w48[14];
  /* #146: @37 = (@37+@51) */
  w37 += w51;
  /* #147: @72 = zeros(8x8) */
  casadi_clear(w72, 64);
  /* #148: @51 = 0.5 */
  w51 = 5.0000000000000000e-01;
  /* #149: @3 = (@51*@3) */
  for (i=0, rr=w03, cs=wr03; i<8; ++i) (*rr++)  = (w51*(*cs++));
  /* #150: @73 = vertcat(@23, @17, @18, @19, @23, @20, @21, @22) */
  rr=w73;
  *rr++ = w23;
  *rr++ = w17;
  *rr++ = w18;
  *rr++ = w19;
  *rr++ = w23;
  *rr++ = w20;
  *rr++ = w21;
  *rr++ = w22;
  /* #151: @73 = @73' */
  /* #152: @72 = mac(@3,@73,@72) */
  for (i=0, rr=w72; i<8; ++i) for (j=0; j<8; ++j, ++rr) for (k=0, cs=w03+j, ct=w73+i*1; k<1; ++k) *rr += cs[k*8]**ct++;
  /* #153: @74 = @72' */
  for (i=0, rr=w74, cs=w72; i<8; ++i) for (j=0; j<8; ++j) rr[i+j*8] = *cs++;
  /* #154: {@75, @76} = horzsplit(@74) */
  casadi_copy(w74, 32, w75);
  casadi_copy(w74+32, 32, w76);
  /* #155: @77 = @76' */
  for (i=0, rr=w77, cs=w76; i<4; ++i) for (j=0; j<8; ++j) rr[i+j*4] = *cs++;
  /* #156: {@27, @26} = horzsplit(@77) */
  casadi_copy(w77, 16, w27);
  casadi_copy(w77+16, 16, w26);
  /* #157: @77 = @75' */
  for (i=0, rr=w77, cs=w75; i<4; ++i) for (j=0; j<8; ++j) rr[i+j*4] = *cs++;
  /* #158: {@78, NULL} = horzsplit(@77) */
  casadi_copy(w77, 16, w78);
  /* #159: @26 = (@26+@78) */
  for (i=0, rr=w26, cs=w78; i<16; ++i) (*rr++) += (*cs++);
  /* #160: @78 = @26' */
  for (i=0, rr=w78, cs=w26; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #161: {@8, @24, @1, @30} = horzsplit(@78) */
  casadi_copy(w78, 4, w08);
  casadi_copy(w78+4, 4, w24);
  casadi_copy(w78+8, 4, w01);
  casadi_copy(w78+12, 4, w30);
  /* #162: @30 = @30' */
  /* #163: {@23, @51, @79, @80} = horzsplit(@30) */
  w23 = w30[0];
  w51 = w30[1];
  w79 = w30[2];
  w80 = w30[3];
  /* #164: @37 = (@37+@80) */
  w37 += w80;
  /* #165: @1 = @1' */
  /* #166: {@80, @81, @82, @83} = horzsplit(@1) */
  w80 = w01[0];
  w81 = w01[1];
  w82 = w01[2];
  w83 = w01[3];
  /* #167: @37 = (@37+@82) */
  w37 += w82;
  /* #168: @24 = @24' */
  /* #169: {@82, @84, @85, @86} = horzsplit(@24) */
  w82 = w24[0];
  w84 = w24[1];
  w85 = w24[2];
  w86 = w24[3];
  /* #170: @37 = (@37+@84) */
  w37 += w84;
  /* #171: @8 = @8' */
  /* #172: {@84, @87, @88, @89} = horzsplit(@8) */
  w84 = w08[0];
  w87 = w08[1];
  w88 = w08[2];
  w89 = w08[3];
  /* #173: @37 = (@37+@84) */
  w37 += w84;
  /* #174: output[0][0] = @37 */
  if (res[0]) res[0][0] = w37;
  /* #175: @36 = (@36+@40) */
  w36 += w40;
  /* #176: @41 = (@41-@36) */
  w41 -= w36;
  /* #177: @41 = (@41+@45) */
  w41 += w45;
  /* #178: @41 = (@41+@54) */
  w41 += w54;
  /* #179: @41 = (@41+@79) */
  w41 += w79;
  /* #180: @41 = (@41-@83) */
  w41 -= w83;
  /* #181: @41 = (@41+@82) */
  w41 += w82;
  /* #182: @41 = (@41-@87) */
  w41 -= w87;
  /* #183: output[0][1] = @41 */
  if (res[0]) res[0][1] = w41;
  /* #184: @38 = (@38+@44) */
  w38 += w44;
  /* #185: @33 = (@33-@38) */
  w33 -= w38;
  /* #186: @33 = (@33+@46) */
  w33 += w46;
  /* #187: @33 = (@33+@32) */
  w33 += w32;
  /* #188: @33 = (@33-@51) */
  w33 -= w51;
  /* #189: @33 = (@33+@80) */
  w33 += w80;
  /* #190: @33 = (@33+@86) */
  w33 += w86;
  /* #191: @33 = (@33-@88) */
  w33 -= w88;
  /* #192: output[0][2] = @33 */
  if (res[0]) res[0][2] = w33;
  /* #193: @31 = (@31+@39) */
  w31 += w39;
  /* #194: @43 = (@43-@31) */
  w43 -= w31;
  /* #195: @43 = (@43+@47) */
  w43 += w47;
  /* #196: @43 = (@43+@53) */
  w43 += w53;
  /* #197: @43 = (@43+@23) */
  w43 += w23;
  /* #198: @43 = (@43+@81) */
  w43 += w81;
  /* #199: @43 = (@43-@85) */
  w43 -= w85;
  /* #200: @43 = (@43-@89) */
  w43 -= w89;
  /* #201: output[0][3] = @43 */
  if (res[0]) res[0][3] = w43;
  /* #202: @78 = @27' */
  for (i=0, rr=w78, cs=w27; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #203: {@8, @24, @1, @30} = horzsplit(@78) */
  casadi_copy(w78, 4, w08);
  casadi_copy(w78+4, 4, w24);
  casadi_copy(w78+8, 4, w01);
  casadi_copy(w78+12, 4, w30);
  /* #204: @30 = @30' */
  /* #205: {@43, @89, @85, @81} = horzsplit(@30) */
  w43 = w30[0];
  w89 = w30[1];
  w85 = w30[2];
  w81 = w30[3];
  /* #206: @57 = (@57+@81) */
  w57 += w81;
  /* #207: @1 = @1' */
  /* #208: {@81, @23, @53, @47} = horzsplit(@1) */
  w81 = w01[0];
  w23 = w01[1];
  w53 = w01[2];
  w47 = w01[3];
  /* #209: @57 = (@57+@53) */
  w57 += w53;
  /* #210: @24 = @24' */
  /* #211: {@53, @31, @39, @33} = horzsplit(@24) */
  w53 = w24[0];
  w31 = w24[1];
  w39 = w24[2];
  w33 = w24[3];
  /* #212: @57 = (@57+@31) */
  w57 += w31;
  /* #213: @8 = @8' */
  /* #214: {@31, @88, @86, @80} = horzsplit(@8) */
  w31 = w08[0];
  w88 = w08[1];
  w86 = w08[2];
  w80 = w08[3];
  /* #215: @57 = (@57+@31) */
  w57 += w31;
  /* #216: output[0][4] = @57 */
  if (res[0]) res[0][4] = w57;
  /* #217: @62 = (@62+@85) */
  w62 += w85;
  /* #218: @62 = (@62-@47) */
  w62 -= w47;
  /* #219: @62 = (@62+@53) */
  w62 += w53;
  /* #220: @62 = (@62-@88) */
  w62 -= w88;
  /* #221: output[0][5] = @62 */
  if (res[0]) res[0][5] = w62;
  /* #222: @63 = (@63-@89) */
  w63 -= w89;
  /* #223: @63 = (@63+@81) */
  w63 += w81;
  /* #224: @63 = (@63+@33) */
  w63 += w33;
  /* #225: @63 = (@63-@86) */
  w63 -= w86;
  /* #226: output[0][6] = @63 */
  if (res[0]) res[0][6] = w63;
  /* #227: @64 = (@64+@43) */
  w64 += w43;
  /* #228: @64 = (@64+@23) */
  w64 += w23;
  /* #229: @64 = (@64-@39) */
  w64 -= w39;
  /* #230: @64 = (@64-@80) */
  w64 -= w80;
  /* #231: output[0][7] = @64 */
  if (res[0]) res[0][7] = w64;
  /* #232: {@64, @80, @39} = vertsplit(@5) */
  w64 = wr05[0];
  w80 = wr05[1];
  w39 = wr05[2];
  /* #233: @23 = (@22*@80) */
  w23  = (w22*w80);
  /* #234: @43 = (@21*@39) */
  w43  = (w21*w39);
  /* #235: @23 = (@23-@43) */
  w23 -= w43;
  /* #236: @61 = @2[8:11] */
  for (rr=w61, cs=w02+8; cs!=w02+11; cs+=1) *rr++ = *cs;
  /* #237: @34 = mac(@58,@61,@34) */
  for (i=0, rr=w34; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=wr58+j, ct=w61+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #238: @43 = @34[1] */
  for (rr=(&w43), cs=w34+1; cs!=w34+2; cs+=1) *rr++ = *cs;
  /* #239: @63 = (@43*@52) */
  w63  = (w43*w52);
  /* #240: @23 = (@23+@63) */
  w23 += w63;
  /* #241: @63 = @34[2] */
  for (rr=(&w63), cs=w34+2; cs!=w34+3; cs+=1) *rr++ = *cs;
  /* #242: @86 = (@63*@55) */
  w86  = (w63*w55);
  /* #243: @23 = (@23-@86) */
  w23 -= w86;
  /* #244: @23 = (@23+@65) */
  w23 += w65;
  /* #245: @73 = zeros(8x1) */
  casadi_clear(w73, 8);
  /* #246: @8 = horzcat(@9, @42, @49, @50) */
  rr=w08;
  *rr++ = w09;
  *rr++ = w42;
  *rr++ = w49;
  *rr++ = w50;
  /* #247: @8 = @8' */
  /* #248: @24 = horzcat(@10, @9, @50, @11) */
  rr=w24;
  *rr++ = w10;
  *rr++ = w09;
  *rr++ = w50;
  *rr++ = w11;
  /* #249: @24 = @24' */
  /* #250: @1 = horzcat(@11, @12, @9, @42) */
  rr=w01;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w09;
  *rr++ = w42;
  /* #251: @1 = @1' */
  /* #252: @30 = horzcat(@12, @49, @10, @9) */
  rr=w30;
  *rr++ = w12;
  *rr++ = w49;
  *rr++ = w10;
  *rr++ = w09;
  /* #253: @30 = @30' */
  /* #254: @78 = horzcat(@8, @24, @1, @30) */
  rr=w78;
  for (i=0, cs=w08; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w24; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w01; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w30; i<4; ++i) *rr++ = *cs++;
  /* #255: @27 = @78' */
  for (i=0, rr=w27, cs=w78; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #256: @77 = horzcat(@27, @0) */
  rr=w77;
  for (i=0, cs=w27; i<16; ++i) *rr++ = *cs++;
  for (i=0, cs=w00; i<16; ++i) *rr++ = *cs++;
  /* #257: @75 = @77' */
  for (i=0, rr=w75, cs=w77; i<8; ++i) for (j=0; j<4; ++j) rr[i+j*8] = *cs++;
  /* #258: @12 = (-@14) */
  w12 = (- w14 );
  /* #259: @49 = (-@15) */
  w49 = (- w15 );
  /* #260: @10 = (-@16) */
  w10 = (- w16 );
  /* #261: @8 = horzcat(@13, @12, @49, @10) */
  rr=w08;
  *rr++ = w13;
  *rr++ = w12;
  *rr++ = w49;
  *rr++ = w10;
  /* #262: @8 = @8' */
  /* #263: @24 = horzcat(@14, @13, @10, @15) */
  rr=w24;
  *rr++ = w14;
  *rr++ = w13;
  *rr++ = w10;
  *rr++ = w15;
  /* #264: @24 = @24' */
  /* #265: @1 = horzcat(@15, @16, @13, @12) */
  rr=w01;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w13;
  *rr++ = w12;
  /* #266: @1 = @1' */
  /* #267: @30 = horzcat(@16, @49, @14, @13) */
  rr=w30;
  *rr++ = w16;
  *rr++ = w49;
  *rr++ = w14;
  *rr++ = w13;
  /* #268: @30 = @30' */
  /* #269: @0 = horzcat(@8, @24, @1, @30) */
  rr=w00;
  for (i=0, cs=w08; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w24; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w01; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w30; i<4; ++i) *rr++ = *cs++;
  /* #270: @78 = @0' */
  for (i=0, rr=w78, cs=w00; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #271: @77 = horzcat(@78, @27) */
  rr=w77;
  for (i=0, cs=w78; i<16; ++i) *rr++ = *cs++;
  for (i=0, cs=w27; i<16; ++i) *rr++ = *cs++;
  /* #272: @76 = @77' */
  for (i=0, rr=w76, cs=w77; i<8; ++i) for (j=0; j<4; ++j) rr[i+j*8] = *cs++;
  /* #273: @74 = horzcat(@75, @76) */
  rr=w74;
  for (i=0, cs=w75; i<32; ++i) *rr++ = *cs++;
  for (i=0, cs=w76; i<32; ++i) *rr++ = *cs++;
  /* #274: @73 = mac(@74,@3,@73) */
  for (i=0, rr=w73; i<1; ++i) for (j=0; j<8; ++j, ++rr) for (k=0, cs=w74+j, ct=w03+i*8; k<8; ++k) *rr += cs[k*8]**ct++;
  /* #275: {NULL, @16, @49, @14, NULL, @13, @15, @12} = vertsplit(@73) */
  w16 = w73[1];
  w49 = w73[2];
  w14 = w73[3];
  w13 = w73[5];
  w15 = w73[6];
  w12 = w73[7];
  /* #276: @23 = (@23+@16) */
  w23 += w16;
  /* #277: output[0][8] = @23 */
  if (res[0]) res[0][8] = w23;
  /* #278: @23 = (@20*@39) */
  w23  = (w20*w39);
  /* #279: @22 = (@22*@64) */
  w22 *= w64;
  /* #280: @23 = (@23-@22) */
  w23 -= w22;
  /* #281: @22 = @34[0] */
  for (rr=(&w22), cs=w34+0; cs!=w34+1; cs+=1) *rr++ = *cs;
  /* #282: @52 = (@22*@52) */
  w52  = (w22*w52);
  /* #283: @23 = (@23-@52) */
  w23 -= w52;
  /* #284: @63 = (@63*@56) */
  w63 *= w56;
  /* #285: @23 = (@23+@63) */
  w23 += w63;
  /* #286: @23 = (@23+@66) */
  w23 += w66;
  /* #287: @23 = (@23+@49) */
  w23 += w49;
  /* #288: output[0][9] = @23 */
  if (res[0]) res[0][9] = w23;
  /* #289: @21 = (@21*@64) */
  w21 *= w64;
  /* #290: @20 = (@20*@80) */
  w20 *= w80;
  /* #291: @21 = (@21-@20) */
  w21 -= w20;
  /* #292: @22 = (@22*@55) */
  w22 *= w55;
  /* #293: @21 = (@21+@22) */
  w21 += w22;
  /* #294: @43 = (@43*@56) */
  w43 *= w56;
  /* #295: @21 = (@21-@43) */
  w21 -= w43;
  /* #296: @21 = (@21+@67) */
  w21 += w67;
  /* #297: @21 = (@21+@14) */
  w21 += w14;
  /* #298: output[0][10] = @21 */
  if (res[0]) res[0][10] = w21;
  /* #299: @21 = (@18*@39) */
  w21  = (w18*w39);
  /* #300: @14 = (@19*@80) */
  w14  = (w19*w80);
  /* #301: @21 = (@21-@14) */
  w21 -= w14;
  /* #302: @21 = (@21+@68) */
  w21 += w68;
  /* #303: @21 = (@21+@13) */
  w21 += w13;
  /* #304: output[0][11] = @21 */
  if (res[0]) res[0][11] = w21;
  /* #305: @19 = (@19*@64) */
  w19 *= w64;
  /* #306: @39 = (@17*@39) */
  w39  = (w17*w39);
  /* #307: @19 = (@19-@39) */
  w19 -= w39;
  /* #308: @19 = (@19+@69) */
  w19 += w69;
  /* #309: @19 = (@19+@15) */
  w19 += w15;
  /* #310: output[0][12] = @19 */
  if (res[0]) res[0][12] = w19;
  /* #311: @17 = (@17*@80) */
  w17 *= w80;
  /* #312: @18 = (@18*@64) */
  w18 *= w64;
  /* #313: @17 = (@17-@18) */
  w17 -= w18;
  /* #314: @17 = (@17+@70) */
  w17 += w70;
  /* #315: @17 = (@17+@12) */
  w17 += w12;
  /* #316: output[0][13] = @17 */
  if (res[0]) res[0][13] = w17;
  /* #317: output[0][14] = @71 */
  if (res[0]) res[0][14] = w71;
  /* #318: @71 = dot(@7, @5) */
  w71 = casadi_dot(3, w07, wr05);
  /* #319: @90 = zeros(5x1) */
  casadi_clear(w90, 5);
  /* #320: (@90[1:4] += @60) */
  for (rr=w90+1, cs=w60; rr!=w90+4; rr+=1) *rr += *cs++;
  /* #321: {@17, @12, @70, @18, @64} = vertsplit(@90) */
  w17 = w90[0];
  w12 = w90[1];
  w70 = w90[2];
  w18 = w90[3];
  w64 = w90[4];
  /* #322: @71 = (@71+@17) */
  w71 += w17;
  /* #323: output[0][15] = @71 */
  if (res[0]) res[0][15] = w71;
  /* #324: output[0][16] = @12 */
  if (res[0]) res[0][16] = w12;
  /* #325: output[0][17] = @70 */
  if (res[0]) res[0][17] = w70;
  /* #326: output[0][18] = @18 */
  if (res[0]) res[0][18] = w18;
  /* #327: @6 = (@6+@64) */
  w06 += w64;
  /* #328: output[0][19] = @6 */
  if (res[0]) res[0][19] = w06;
  return 0;
}

CASADI_SYMBOL_EXPORT int DQ_Drone_MPCC_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int DQ_Drone_MPCC_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int DQ_Drone_MPCC_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void DQ_Drone_MPCC_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int DQ_Drone_MPCC_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void DQ_Drone_MPCC_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void DQ_Drone_MPCC_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void DQ_Drone_MPCC_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int DQ_Drone_MPCC_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int DQ_Drone_MPCC_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real DQ_Drone_MPCC_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* DQ_Drone_MPCC_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* DQ_Drone_MPCC_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* DQ_Drone_MPCC_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* DQ_Drone_MPCC_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int DQ_Drone_MPCC_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 19;
  if (sz_res) *sz_res = 16;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 476;
  return 0;
}

CASADI_SYMBOL_EXPORT int DQ_Drone_MPCC_expl_vde_adj_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 19*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 16*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 476*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
