/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) DQ_Drone_MPCC_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_norm_2 CASADI_PREFIX(norm_2)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_norm_2(casadi_int n, const casadi_real* x) {
  return sqrt(casadi_dot(n, x, x));
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[3] = {15, 1, 1};
static const casadi_int casadi_s1[3] = {5, 1, 1};
static const casadi_int casadi_s2[3] = {1, 1, 1};

static const casadi_real casadi_c0[3] = {3.2723905139943781e+02, 6.2619368170575160e+02, 6.2622505275946071e+02};
static const casadi_real casadi_c1[9] = 
  {3.0558700000000000e-03, 0., 0., 0., 1.5969500000000000e-03, 0., 0., 0.,
  1.5968700000000000e-03};

/* DQ_Drone_MPCC_expl_ode_fun:(i0[15],i1[5],i2)->(o0[15]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, w00, *w01=w+9, w02, w03, w04, w05, w06, w07, w08, *w09=w+24, *w10=w+28;
  casadi_real *w11=w+32, *w12=w+36, *w13=w+40, *w14=w+56, *w15=w+72, *w16=w+104, w17, w18, w19, w20, w21, w22;
  casadi_real w23, *w24=w+143, *w25=w+159, *w26=w+191, *w27=w+255, w28, w29, w30, w31, *w32=w+323, *w33=w+331, *w34=w+346;
  casadi_real w35, *w36=w+350, *w37=w+355, *w38=w+358, *w40=w+370, w41, w42, *w43=w+375, *w44=w+379;
  const casadi_real *cr, *cs, *ct, *wr39;
  /* #0: @0 = 0.5 */
  w00 = 5.0000000000000000e-01;
  /* #1: @1 = zeros(8x1) */
  casadi_clear(w01, 8);
  /* #2: @2 = input[0][0] */
  w02 = arg[0] ? arg[0][0] : 0;
  /* #3: @3 = input[0][1] */
  w03 = arg[0] ? arg[0][1] : 0;
  /* #4: @4 = (-@3) */
  w04 = (- w03 );
  /* #5: @5 = input[0][2] */
  w05 = arg[0] ? arg[0][2] : 0;
  /* #6: @6 = (-@5) */
  w06 = (- w05 );
  /* #7: @7 = input[0][3] */
  w07 = arg[0] ? arg[0][3] : 0;
  /* #8: @8 = (-@7) */
  w08 = (- w07 );
  /* #9: @9 = horzcat(@2, @4, @6, @8) */
  rr=w09;
  *rr++ = w02;
  *rr++ = w04;
  *rr++ = w06;
  *rr++ = w08;
  /* #10: @9 = @9' */
  /* #11: @10 = horzcat(@3, @2, @8, @5) */
  rr=w10;
  *rr++ = w03;
  *rr++ = w02;
  *rr++ = w08;
  *rr++ = w05;
  /* #12: @10 = @10' */
  /* #13: @11 = horzcat(@5, @7, @2, @4) */
  rr=w11;
  *rr++ = w05;
  *rr++ = w07;
  *rr++ = w02;
  *rr++ = w04;
  /* #14: @11 = @11' */
  /* #15: @12 = horzcat(@7, @6, @3, @2) */
  rr=w12;
  *rr++ = w07;
  *rr++ = w06;
  *rr++ = w03;
  *rr++ = w02;
  /* #16: @12 = @12' */
  /* #17: @13 = horzcat(@9, @10, @11, @12) */
  rr=w13;
  for (i=0, cs=w09; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w10; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w11; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w12; i<4; ++i) *rr++ = *cs++;
  /* #18: @14 = @13' */
  for (i=0, rr=w14, cs=w13; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #19: @13 = zeros(4x4) */
  casadi_clear(w13, 16);
  /* #20: @15 = horzcat(@14, @13) */
  rr=w15;
  for (i=0, cs=w14; i<16; ++i) *rr++ = *cs++;
  for (i=0, cs=w13; i<16; ++i) *rr++ = *cs++;
  /* #21: @16 = @15' */
  for (i=0, rr=w16, cs=w15; i<8; ++i) for (j=0; j<4; ++j) rr[i+j*8] = *cs++;
  /* #22: @17 = input[0][4] */
  w17 = arg[0] ? arg[0][4] : 0;
  /* #23: @18 = input[0][5] */
  w18 = arg[0] ? arg[0][5] : 0;
  /* #24: @19 = (-@18) */
  w19 = (- w18 );
  /* #25: @20 = input[0][6] */
  w20 = arg[0] ? arg[0][6] : 0;
  /* #26: @21 = (-@20) */
  w21 = (- w20 );
  /* #27: @22 = input[0][7] */
  w22 = arg[0] ? arg[0][7] : 0;
  /* #28: @23 = (-@22) */
  w23 = (- w22 );
  /* #29: @9 = horzcat(@17, @19, @21, @23) */
  rr=w09;
  *rr++ = w17;
  *rr++ = w19;
  *rr++ = w21;
  *rr++ = w23;
  /* #30: @9 = @9' */
  /* #31: @10 = horzcat(@18, @17, @23, @20) */
  rr=w10;
  *rr++ = w18;
  *rr++ = w17;
  *rr++ = w23;
  *rr++ = w20;
  /* #32: @10 = @10' */
  /* #33: @11 = horzcat(@20, @22, @17, @19) */
  rr=w11;
  *rr++ = w20;
  *rr++ = w22;
  *rr++ = w17;
  *rr++ = w19;
  /* #34: @11 = @11' */
  /* #35: @12 = horzcat(@22, @21, @18, @17) */
  rr=w12;
  *rr++ = w22;
  *rr++ = w21;
  *rr++ = w18;
  *rr++ = w17;
  /* #36: @12 = @12' */
  /* #37: @13 = horzcat(@9, @10, @11, @12) */
  rr=w13;
  for (i=0, cs=w09; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w10; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w11; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w12; i<4; ++i) *rr++ = *cs++;
  /* #38: @24 = @13' */
  for (i=0, rr=w24, cs=w13; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #39: @15 = horzcat(@24, @14) */
  rr=w15;
  for (i=0, cs=w24; i<16; ++i) *rr++ = *cs++;
  for (i=0, cs=w14; i<16; ++i) *rr++ = *cs++;
  /* #40: @25 = @15' */
  for (i=0, rr=w25, cs=w15; i<8; ++i) for (j=0; j<4; ++j) rr[i+j*8] = *cs++;
  /* #41: @26 = horzcat(@16, @25) */
  rr=w26;
  for (i=0, cs=w16; i<32; ++i) *rr++ = *cs++;
  for (i=0, cs=w25; i<32; ++i) *rr++ = *cs++;
  /* #42: @27 = @26' */
  for (i=0, rr=w27, cs=w26; i<8; ++i) for (j=0; j<8; ++j) rr[i+j*8] = *cs++;
  /* #43: @21 = 0 */
  w21 = 0.;
  /* #44: @19 = input[0][8] */
  w19 = arg[0] ? arg[0][8] : 0;
  /* #45: @23 = input[0][9] */
  w23 = arg[0] ? arg[0][9] : 0;
  /* #46: @28 = input[0][10] */
  w28 = arg[0] ? arg[0][10] : 0;
  /* #47: @29 = input[0][11] */
  w29 = arg[0] ? arg[0][11] : 0;
  /* #48: @30 = input[0][12] */
  w30 = arg[0] ? arg[0][12] : 0;
  /* #49: @31 = input[0][13] */
  w31 = arg[0] ? arg[0][13] : 0;
  /* #50: @32 = vertcat(@21, @19, @23, @28, @21, @29, @30, @31) */
  rr=w32;
  *rr++ = w21;
  *rr++ = w19;
  *rr++ = w23;
  *rr++ = w28;
  *rr++ = w21;
  *rr++ = w29;
  *rr++ = w30;
  *rr++ = w31;
  /* #51: @1 = mac(@27,@32,@1) */
  for (i=0, rr=w01; i<1; ++i) for (j=0; j<8; ++j, ++rr) for (k=0, cs=w27+j, ct=w32+i*8; k<8; ++k) *rr += cs[k*8]**ct++;
  /* #52: @1 = (@0*@1) */
  for (i=0, rr=w01, cs=w01; i<8; ++i) (*rr++)  = (w00*(*cs++));
  /* #53: @0 = input[0][14] */
  w00 = arg[0] ? arg[0][14] : 0;
  /* #54: @33 = vertcat(@2, @3, @5, @7, @17, @18, @20, @22, @19, @23, @28, @29, @30, @31, @0) */
  rr=w33;
  *rr++ = w02;
  *rr++ = w03;
  *rr++ = w05;
  *rr++ = w07;
  *rr++ = w17;
  *rr++ = w18;
  *rr++ = w20;
  *rr++ = w22;
  *rr++ = w19;
  *rr++ = w23;
  *rr++ = w28;
  *rr++ = w29;
  *rr++ = w30;
  *rr++ = w31;
  *rr++ = w00;
  /* #55: @9 = @33[:4] */
  for (rr=w09, cs=w33+0; cs!=w33+4; cs+=1) *rr++ = *cs;
  /* #56: @17 = 10 */
  w17 = 10.;
  /* #57: @18 = 1 */
  w18 = 1.;
  /* #58: @20 = ||@9||_F */
  w20 = casadi_norm_2(4, w09);
  /* #59: @20 = (@18-@20) */
  w20  = (w18-w20);
  /* #60: @17 = (@17*@20) */
  w17 *= w20;
  /* #61: @10 = (@9*@17) */
  for (i=0, rr=w10, cr=w09; i<4; ++i) (*rr++)  = ((*cr++)*w17);
  /* #62: @11 = zeros(4x1) */
  casadi_clear(w11, 4);
  /* #63: @32 = vertcat(@10, @11) */
  rr=w32;
  for (i=0, cs=w10; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w11; i<4; ++i) *rr++ = *cs++;
  /* #64: @1 = (@1+@32) */
  for (i=0, rr=w01, cs=w32; i<8; ++i) (*rr++) += (*cs++);
  /* #65: output[0][0] = @1 */
  casadi_copy(w01, 8, res[0]);
  /* #66: @34 = 
  [[327.239, 00, 00], 
   [00, 626.194, 00], 
   [00, 00, 626.225]] */
  casadi_copy(casadi_c0, 3, w34);
  /* #67: @34 = nonzeros(@34) */
  /* #68: @17 = input[1][0] */
  w17 = arg[1] ? arg[1][0] : 0;
  /* #69: @20 = input[1][1] */
  w20 = arg[1] ? arg[1][1] : 0;
  /* #70: @22 = input[1][2] */
  w22 = arg[1] ? arg[1][2] : 0;
  /* #71: @0 = input[1][3] */
  w00 = arg[1] ? arg[1][3] : 0;
  /* #72: @35 = input[1][4] */
  w35 = arg[1] ? arg[1][4] : 0;
  /* #73: @36 = vertcat(@17, @20, @22, @0, @35) */
  rr=w36;
  *rr++ = w17;
  *rr++ = w20;
  *rr++ = w22;
  *rr++ = w00;
  *rr++ = w35;
  /* #74: @37 = @36[1:4] */
  for (rr=w37, cs=w36+1; cs!=w36+4; cs+=1) *rr++ = *cs;
  /* #75: @38 = zeros(3x1) */
  casadi_clear(w38, 3);
  /* #76: @39 = 
  [[0.00305587, 0, 0], 
   [0, 0.00159695, 0], 
   [0, 0, 0.00159687]] */
  wr39 = casadi_c1;
  /* #77: @40 = @33[8:11] */
  for (rr=w40, cs=w33+8; cs!=w33+11; cs+=1) *rr++ = *cs;
  /* #78: @38 = mac(@39,@40,@38) */
  for (i=0, rr=w38; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=wr39+j, ct=w40+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #79: @20 = @38[2] */
  for (rr=(&w20), cs=w38+2; cs!=w38+3; cs+=1) *rr++ = *cs;
  /* #80: @22 = (@23*@20) */
  w22  = (w23*w20);
  /* #81: @0 = @38[1] */
  for (rr=(&w00), cs=w38+1; cs!=w38+2; cs+=1) *rr++ = *cs;
  /* #82: @41 = (@28*@0) */
  w41  = (w28*w00);
  /* #83: @22 = (@22-@41) */
  w22 -= w41;
  /* #84: @41 = @38[0] */
  for (rr=(&w41), cs=w38+0; cs!=w38+1; cs+=1) *rr++ = *cs;
  /* #85: @42 = (@28*@41) */
  w42  = (w28*w41);
  /* #86: @20 = (@19*@20) */
  w20  = (w19*w20);
  /* #87: @42 = (@42-@20) */
  w42 -= w20;
  /* #88: @0 = (@19*@0) */
  w00  = (w19*w00);
  /* #89: @41 = (@23*@41) */
  w41  = (w23*w41);
  /* #90: @0 = (@0-@41) */
  w00 -= w41;
  /* #91: @38 = vertcat(@22, @42, @0) */
  rr=w38;
  *rr++ = w22;
  *rr++ = w42;
  *rr++ = w00;
  /* #92: @37 = (@37-@38) */
  for (i=0, rr=w37, cs=w38; i<3; ++i) (*rr++) -= (*cs++);
  /* #93: @34 = (@34*@37) */
  for (i=0, rr=w34, cs=w37; i<3; ++i) (*rr++) *= (*cs++);
  /* #94: output[0][1] = @34 */
  if (res[0]) casadi_copy(w34, 3, res[0]+8);
  /* #95: @22 = (@30*@28) */
  w22  = (w30*w28);
  /* #96: @42 = (@31*@23) */
  w42  = (w31*w23);
  /* #97: @22 = (@22-@42) */
  w22 -= w42;
  /* #98: @31 = (@31*@19) */
  w31 *= w19;
  /* #99: @28 = (@29*@28) */
  w28  = (w29*w28);
  /* #100: @31 = (@31-@28) */
  w31 -= w28;
  /* #101: @29 = (@29*@23) */
  w29 *= w23;
  /* #102: @30 = (@30*@19) */
  w30 *= w19;
  /* #103: @29 = (@29-@30) */
  w29 -= w30;
  /* #104: @34 = vertcat(@22, @31, @29) */
  rr=w34;
  *rr++ = w22;
  *rr++ = w31;
  *rr++ = w29;
  /* #105: @10 = horzcat(@2, @3, @5, @7) */
  rr=w10;
  *rr++ = w02;
  *rr++ = w03;
  *rr++ = w05;
  *rr++ = w07;
  /* #106: @10 = @10' */
  /* #107: @12 = horzcat(@4, @2, @7, @6) */
  rr=w12;
  *rr++ = w04;
  *rr++ = w02;
  *rr++ = w07;
  *rr++ = w06;
  /* #108: @12 = @12' */
  /* #109: @43 = horzcat(@6, @8, @2, @3) */
  rr=w43;
  *rr++ = w06;
  *rr++ = w08;
  *rr++ = w02;
  *rr++ = w03;
  /* #110: @43 = @43' */
  /* #111: @44 = horzcat(@8, @5, @4, @2) */
  rr=w44;
  *rr++ = w08;
  *rr++ = w05;
  *rr++ = w04;
  *rr++ = w02;
  /* #112: @44 = @44' */
  /* #113: @24 = horzcat(@10, @12, @43, @44) */
  rr=w24;
  for (i=0, cs=w10; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w12; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w43; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w44; i<4; ++i) *rr++ = *cs++;
  /* #114: @14 = @24' */
  for (i=0, rr=w14, cs=w24; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #115: @8 = 9.81 */
  w08 = 9.8100000000000005e+00;
  /* #116: @37 = vertcat(@21, @21, @18) */
  rr=w37;
  *rr++ = w21;
  *rr++ = w21;
  *rr++ = w18;
  /* #117: @38 = (@8*@37) */
  for (i=0, rr=w38, cs=w37; i<3; ++i) (*rr++)  = (w08*(*cs++));
  /* #118: @10 = vertcat(@21, @38) */
  rr=w10;
  *rr++ = w21;
  for (i=0, cs=w38; i<3; ++i) *rr++ = *cs++;
  /* #119: @12 = mac(@14,@10,@11) */
  casadi_copy(w11, 4, w12);
  for (i=0, rr=w12; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, cs=w14+j, ct=w10+i*4; k<4; ++k) *rr += cs[k*4]**ct++;
  /* #120: @21 = @12[0] */
  for (rr=(&w21), cs=w12+0; cs!=w12+1; cs+=1) *rr++ = *cs;
  /* #121: @8 = @12[1] */
  for (rr=(&w08), cs=w12+1; cs!=w12+2; cs+=1) *rr++ = *cs;
  /* #122: @18 = (-@8) */
  w18 = (- w08 );
  /* #123: @5 = @12[2] */
  for (rr=(&w05), cs=w12+2; cs!=w12+3; cs+=1) *rr++ = *cs;
  /* #124: @4 = (-@5) */
  w04 = (- w05 );
  /* #125: @2 = @12[3] */
  for (rr=(&w02), cs=w12+3; cs!=w12+4; cs+=1) *rr++ = *cs;
  /* #126: @6 = (-@2) */
  w06 = (- w02 );
  /* #127: @12 = horzcat(@21, @18, @4, @6) */
  rr=w12;
  *rr++ = w21;
  *rr++ = w18;
  *rr++ = w04;
  *rr++ = w06;
  /* #128: @12 = @12' */
  /* #129: @10 = horzcat(@8, @21, @6, @5) */
  rr=w10;
  *rr++ = w08;
  *rr++ = w21;
  *rr++ = w06;
  *rr++ = w05;
  /* #130: @10 = @10' */
  /* #131: @43 = horzcat(@5, @2, @21, @18) */
  rr=w43;
  *rr++ = w05;
  *rr++ = w02;
  *rr++ = w21;
  *rr++ = w18;
  /* #132: @43 = @43' */
  /* #133: @44 = horzcat(@2, @4, @8, @21) */
  rr=w44;
  *rr++ = w02;
  *rr++ = w04;
  *rr++ = w08;
  *rr++ = w21;
  /* #134: @44 = @44' */
  /* #135: @14 = horzcat(@12, @10, @43, @44) */
  rr=w14;
  for (i=0, cs=w12; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w10; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w43; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w44; i<4; ++i) *rr++ = *cs++;
  /* #136: @24 = @14' */
  for (i=0, rr=w24, cs=w14; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #137: @11 = mac(@24,@9,@11) */
  for (i=0, rr=w11; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, cs=w24+j, ct=w09+i*4; k<4; ++k) *rr += cs[k*4]**ct++;
  /* #138: @38 = @11[1:4] */
  for (rr=w38, cs=w11+1; cs!=w11+4; cs+=1) *rr++ = *cs;
  /* #139: @34 = (@34-@38) */
  for (i=0, rr=w34, cs=w38; i<3; ++i) (*rr++) -= (*cs++);
  /* #140: @37 = (@17*@37) */
  for (i=0, rr=w37, cs=w37; i<3; ++i) (*rr++)  = (w17*(*cs++));
  /* #141: @34 = (@34+@37) */
  for (i=0, rr=w34, cs=w37; i<3; ++i) (*rr++) += (*cs++);
  /* #142: output[0][2] = @34 */
  if (res[0]) casadi_copy(w34, 3, res[0]+11);
  /* #143: output[0][3] = @35 */
  if (res[0]) res[0][14] = w35;
  return 0;
}

CASADI_SYMBOL_EXPORT int DQ_Drone_MPCC_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int DQ_Drone_MPCC_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int DQ_Drone_MPCC_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void DQ_Drone_MPCC_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int DQ_Drone_MPCC_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void DQ_Drone_MPCC_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void DQ_Drone_MPCC_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void DQ_Drone_MPCC_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int DQ_Drone_MPCC_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int DQ_Drone_MPCC_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real DQ_Drone_MPCC_expl_ode_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* DQ_Drone_MPCC_expl_ode_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* DQ_Drone_MPCC_expl_ode_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* DQ_Drone_MPCC_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* DQ_Drone_MPCC_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int DQ_Drone_MPCC_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 18;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 383;
  return 0;
}

CASADI_SYMBOL_EXPORT int DQ_Drone_MPCC_expl_ode_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 18*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 383*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
