/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Drone_ode_mpcc_rate_mujoco_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_norm_2 CASADI_PREFIX(norm_2)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_norm_2(casadi_int n, const casadi_real* x) {
  return sqrt(casadi_dot(n, x, x));
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[3] = {14, 1, 1};
static const casadi_int casadi_s1[3] = {5, 1, 1};
static const casadi_int casadi_s2[3] = {1, 1, 1};
static const casadi_int casadi_s3[19] = 
  {19, 1, 0, 15, 3, 4, 5, 6,
  7, 8, 9, 10, 11, 12, 14, 15,
  16, 17, 18};

static const casadi_real casadi_c0[9] = 
  {1., 0., 0., 0., 1., 0., 0., 0.,
  1.};

static const casadi_real casadi_zeros[14] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0.};

/* Drone_ode_mpcc_rate_mujoco_expl_vde_adj:(i0[14],i1[14],i2[5],i3)->(o0[19x1,15nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, w01, w02, w03, *w04=w+20, *w05=w+23, *w06=w+27, w07, w08, w09, w10, w11;
  casadi_real w12, w13, *w14=w+37, w15, w16, w17, *w18=w+49, w19, *w20=w+54, w21, w22, *w23=w+60;
  casadi_real w24, *w25=w+70, *w26=w+73, *w27=w+82, *w28=w+91, *w29=w+100, *w30=w+109, *w31=w+118, w32;
  const casadi_real *cr, *cs, *ct, *wr00, *wr04, *wr05, *wr06, *wr27;
  /* #0: @0 = input[1][0] */
  wr00 = arg[1] ? arg[1] : casadi_zeros;
  /* #1: {@1, @2, @3, @4, @5, @6, @7} = vertsplit(@0) */
  w01 = wr00[0];
  w02 = wr00[1];
  w03 = wr00[2];
  wr04 = wr00+3;
  wr05 = wr00+6;
  wr06 = wr00+10;
  w07 = wr00[13];
  /* #2: output[0][0] = @1 */
  if (res[0]) res[0][0] = w01;
  /* #3: output[0][1] = @2 */
  if (res[0]) res[0][1] = w02;
  /* #4: output[0][2] = @3 */
  if (res[0]) res[0][2] = w03;
  /* #5: @3 = input[0][12] */
  w03 = arg[0] ? arg[0][12] : 0;
  /* #6: @2 = 0.5 */
  w02 = 5.0000000000000000e-01;
  /* #7: @5 = (@2*@5) */
  for (i=0, rr=w05, cs=wr05; i<4; ++i) (*rr++)  = (w02*(*cs++));
  /* #8: {@2, @1, @8, @9} = vertsplit(@5) */
  w02 = w05[0];
  w01 = w05[1];
  w08 = w05[2];
  w09 = w05[3];
  /* #9: @10 = (@3*@9) */
  w10  = (w03*w09);
  /* #10: @11 = input[0][11] */
  w11 = arg[0] ? arg[0][11] : 0;
  /* #11: @12 = (@11*@8) */
  w12  = (w11*w08);
  /* #12: @10 = (@10+@12) */
  w10 += w12;
  /* #13: @12 = input[0][10] */
  w12 = arg[0] ? arg[0][10] : 0;
  /* #14: @13 = (@12*@1) */
  w13  = (w12*w01);
  /* #15: @10 = (@10+@13) */
  w10 += w13;
  /* #16: @5 = zeros(4x1) */
  casadi_clear(w05, 4);
  /* #17: @14 = zeros(3x3) */
  casadi_clear(w14, 9);
  /* #18: @13 = input[0][6] */
  w13 = arg[0] ? arg[0][6] : 0;
  /* #19: @15 = input[0][7] */
  w15 = arg[0] ? arg[0][7] : 0;
  /* #20: @16 = input[0][8] */
  w16 = arg[0] ? arg[0][8] : 0;
  /* #21: @17 = input[0][9] */
  w17 = arg[0] ? arg[0][9] : 0;
  /* #22: @18 = vertcat(@13, @15, @16, @17) */
  rr=w18;
  *rr++ = w13;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w17;
  /* #23: @19 = ||@18||_F */
  w19 = casadi_norm_2(4, w18);
  /* #24: @20 = (@18/@19) */
  for (i=0, rr=w20, cr=w18; i<4; ++i) (*rr++)  = ((*cr++)/w19);
  /* #25: @21 = @20[3] */
  for (rr=(&w21), cs=w20+3; cs!=w20+4; cs+=1) *rr++ = *cs;
  /* #26: @22 = (-@21) */
  w22 = (- w21 );
  /* #27: @23 = @14; (@23[3] = @22) */
  casadi_copy(w14, 9, w23);
  for (rr=w23+3, cs=(&w22); rr!=w23+4; rr+=1) *rr = *cs++;
  /* #28: @22 = @20[2] */
  for (rr=(&w22), cs=w20+2; cs!=w20+3; cs+=1) *rr++ = *cs;
  /* #29: (@23[6] = @22) */
  for (rr=w23+6, cs=(&w22); rr!=w23+7; rr+=1) *rr = *cs++;
  /* #30: (@23[1] = @21) */
  for (rr=w23+1, cs=(&w21); rr!=w23+2; rr+=1) *rr = *cs++;
  /* #31: @21 = @20[1] */
  for (rr=(&w21), cs=w20+1; cs!=w20+2; cs+=1) *rr++ = *cs;
  /* #32: @24 = (-@21) */
  w24 = (- w21 );
  /* #33: (@23[7] = @24) */
  for (rr=w23+7, cs=(&w24); rr!=w23+8; rr+=1) *rr = *cs++;
  /* #34: @22 = (-@22) */
  w22 = (- w22 );
  /* #35: (@23[2] = @22) */
  for (rr=w23+2, cs=(&w22); rr!=w23+3; rr+=1) *rr = *cs++;
  /* #36: (@23[5] = @21) */
  for (rr=w23+5, cs=(&w21); rr!=w23+6; rr+=1) *rr = *cs++;
  /* #37: @21 = 0.925926 */
  w21 = 9.2592592592592582e-01;
  /* #38: @4 = (@21*@4) */
  for (i=0, rr=w04, cs=wr04; i<3; ++i) (*rr++)  = (w21*(*cs++));
  /* #39: @21 = 0 */
  w21 = 0.;
  /* #40: @22 = input[2][0] */
  w22 = arg[2] ? arg[2][0] : 0;
  /* #41: @25 = vertcat(@21, @21, @22) */
  rr=w25;
  *rr++ = w21;
  *rr++ = w21;
  *rr++ = w22;
  /* #42: @25 = @25' */
  /* #43: @26 = mac(@4,@25,@14) */
  casadi_copy(w14, 9, w26);
  for (i=0, rr=w26; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w04+j, ct=w25+i*1; k<1; ++k) *rr += cs[k*3]**ct++;
  /* #44: @22 = dot(@23, @26) */
  w22 = casadi_dot(9, w23, w26);
  /* #45: @22 = (2.*@22) */
  w22 = (2.* w22 );
  /* #46: (@5[0] += @22) */
  for (rr=w05+0, cs=(&w22); rr!=w05+1; rr+=1) *rr += *cs++;
  /* #47: @22 = @20[0] */
  for (rr=(&w22), cs=w20+0; cs!=w20+1; cs+=1) *rr++ = *cs;
  /* #48: @22 = (2.*@22) */
  w22 = (2.* w22 );
  /* #49: @27 = (@22*@26) */
  for (i=0, rr=w27, cs=w26; i<9; ++i) (*rr++)  = (w22*(*cs++));
  /* #50: @28 = (2.*@23) */
  for (i=0, rr=w28, cs=w23; i<9; ++i) *rr++ = (2.* *cs++ );
  /* #51: @29 = @28' */
  for (i=0, rr=w29, cs=w28; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #52: @30 = mac(@29,@26,@14) */
  casadi_copy(w14, 9, w30);
  for (i=0, rr=w30; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w29+j, ct=w26+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #53: @27 = (@27+@30) */
  for (i=0, rr=w27, cs=w30; i<9; ++i) (*rr++) += (*cs++);
  /* #54: @30 = @23' */
  for (i=0, rr=w30, cs=w23; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #55: @29 = mac(@26,@30,@14) */
  casadi_copy(w14, 9, w29);
  for (i=0, rr=w29; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w26+j, ct=w30+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #56: @29 = (2.*@29) */
  for (i=0, rr=w29, cs=w29; i<9; ++i) *rr++ = (2.* *cs++ );
  /* #57: @27 = (@27+@29) */
  for (i=0, rr=w27, cs=w29; i<9; ++i) (*rr++) += (*cs++);
  /* #58: @24 = @27[5] */
  for (rr=(&w24), cs=w27+5; cs!=w27+6; cs+=1) *rr++ = *cs;
  /* #59: (@5[1] += @24) */
  for (rr=w05+1, cs=(&w24); rr!=w05+2; rr+=1) *rr += *cs++;
  /* #60: (@27[5] = @21) */
  for (rr=w27+5, cs=(&w21); rr!=w27+6; rr+=1) *rr = *cs++;
  /* #61: @24 = @27[2] */
  for (rr=(&w24), cs=w27+2; cs!=w27+3; cs+=1) *rr++ = *cs;
  /* #62: @24 = (-@24) */
  w24 = (- w24 );
  /* #63: (@5[2] += @24) */
  for (rr=w05+2, cs=(&w24); rr!=w05+3; rr+=1) *rr += *cs++;
  /* #64: (@27[2] = @21) */
  for (rr=w27+2, cs=(&w21); rr!=w27+3; rr+=1) *rr = *cs++;
  /* #65: @24 = @27[7] */
  for (rr=(&w24), cs=w27+7; cs!=w27+8; cs+=1) *rr++ = *cs;
  /* #66: @24 = (-@24) */
  w24 = (- w24 );
  /* #67: (@5[1] += @24) */
  for (rr=w05+1, cs=(&w24); rr!=w05+2; rr+=1) *rr += *cs++;
  /* #68: (@27[7] = @21) */
  for (rr=w27+7, cs=(&w21); rr!=w27+8; rr+=1) *rr = *cs++;
  /* #69: @24 = @27[1] */
  for (rr=(&w24), cs=w27+1; cs!=w27+2; cs+=1) *rr++ = *cs;
  /* #70: (@5[3] += @24) */
  for (rr=w05+3, cs=(&w24); rr!=w05+4; rr+=1) *rr += *cs++;
  /* #71: (@27[1] = @21) */
  for (rr=w27+1, cs=(&w21); rr!=w27+2; rr+=1) *rr = *cs++;
  /* #72: @24 = @27[6] */
  for (rr=(&w24), cs=w27+6; cs!=w27+7; cs+=1) *rr++ = *cs;
  /* #73: (@5[2] += @24) */
  for (rr=w05+2, cs=(&w24); rr!=w05+3; rr+=1) *rr += *cs++;
  /* #74: (@27[6] = @21) */
  for (rr=w27+6, cs=(&w21); rr!=w27+7; rr+=1) *rr = *cs++;
  /* #75: @21 = @27[3] */
  for (rr=(&w21), cs=w27+3; cs!=w27+4; cs+=1) *rr++ = *cs;
  /* #76: @21 = (-@21) */
  w21 = (- w21 );
  /* #77: (@5[3] += @21) */
  for (rr=w05+3, cs=(&w21); rr!=w05+4; rr+=1) *rr += *cs++;
  /* #78: @31 = (@5/@19) */
  for (i=0, rr=w31, cr=w05; i<4; ++i) (*rr++)  = ((*cr++)/w19);
  /* #79: @20 = (@20/@19) */
  for (i=0, rr=w20; i<4; ++i) (*rr++) /= w19;
  /* #80: @20 = (-@20) */
  for (i=0, rr=w20, cs=w20; i<4; ++i) *rr++ = (- *cs++ );
  /* #81: @21 = dot(@20, @5) */
  w21 = casadi_dot(4, w20, w05);
  /* #82: @21 = (@21/@19) */
  w21 /= w19;
  /* #83: @18 = (@21*@18) */
  for (i=0, rr=w18, cs=w18; i<4; ++i) (*rr++)  = (w21*(*cs++));
  /* #84: @31 = (@31+@18) */
  for (i=0, rr=w31, cs=w18; i<4; ++i) (*rr++) += (*cs++);
  /* #85: {@21, @19, @24, @32} = vertsplit(@31) */
  w21 = w31[0];
  w19 = w31[1];
  w24 = w31[2];
  w32 = w31[3];
  /* #86: @10 = (@10+@21) */
  w10 += w21;
  /* #87: output[0][3] = @10 */
  if (res[0]) res[0][3] = w10;
  /* #88: @10 = (@11*@9) */
  w10  = (w11*w09);
  /* #89: @21 = (@3*@8) */
  w21  = (w03*w08);
  /* #90: @10 = (@10-@21) */
  w10 -= w21;
  /* #91: @21 = (@12*@2) */
  w21  = (w12*w02);
  /* #92: @10 = (@10-@21) */
  w10 -= w21;
  /* #93: @10 = (@10+@19) */
  w10 += w19;
  /* #94: output[0][4] = @10 */
  if (res[0]) res[0][4] = w10;
  /* #95: @10 = (@3*@1) */
  w10  = (w03*w01);
  /* #96: @19 = (@12*@9) */
  w19  = (w12*w09);
  /* #97: @10 = (@10-@19) */
  w10 -= w19;
  /* #98: @19 = (@11*@2) */
  w19  = (w11*w02);
  /* #99: @10 = (@10-@19) */
  w10 -= w19;
  /* #100: @10 = (@10+@24) */
  w10 += w24;
  /* #101: output[0][5] = @10 */
  if (res[0]) res[0][5] = w10;
  /* #102: @12 = (@12*@8) */
  w12 *= w08;
  /* #103: @11 = (@11*@1) */
  w11 *= w01;
  /* #104: @12 = (@12-@11) */
  w12 -= w11;
  /* #105: @3 = (@3*@2) */
  w03 *= w02;
  /* #106: @12 = (@12-@3) */
  w12 -= w03;
  /* #107: @12 = (@12+@32) */
  w12 += w32;
  /* #108: output[0][6] = @12 */
  if (res[0]) res[0][6] = w12;
  /* #109: @12 = 33.3333 */
  w12 = 3.3333333333333336e+01;
  /* #110: @6 = (@12*@6) */
  for (i=0, rr=w06, cs=wr06; i<3; ++i) (*rr++)  = (w12*(*cs++));
  /* #111: @25 = (-@6) */
  for (i=0, rr=w25, cs=w06; i<3; ++i) *rr++ = (- *cs++ );
  /* #112: {@12, @32, @3} = vertsplit(@25) */
  w12 = w25[0];
  w32 = w25[1];
  w03 = w25[2];
  /* #113: @11 = (@16*@9) */
  w11  = (w16*w09);
  /* #114: @12 = (@12-@11) */
  w12 -= w11;
  /* #115: @11 = (@17*@8) */
  w11  = (w17*w08);
  /* #116: @12 = (@12+@11) */
  w12 += w11;
  /* #117: @11 = (@13*@1) */
  w11  = (w13*w01);
  /* #118: @12 = (@12+@11) */
  w12 += w11;
  /* #119: @11 = (@15*@2) */
  w11  = (w15*w02);
  /* #120: @12 = (@12-@11) */
  w12 -= w11;
  /* #121: output[0][7] = @12 */
  if (res[0]) res[0][7] = w12;
  /* #122: @12 = (@15*@9) */
  w12  = (w15*w09);
  /* #123: @32 = (@32+@12) */
  w32 += w12;
  /* #124: @12 = (@13*@8) */
  w12  = (w13*w08);
  /* #125: @32 = (@32+@12) */
  w32 += w12;
  /* #126: @12 = (@17*@1) */
  w12  = (w17*w01);
  /* #127: @32 = (@32-@12) */
  w32 -= w12;
  /* #128: @12 = (@16*@2) */
  w12  = (w16*w02);
  /* #129: @32 = (@32-@12) */
  w32 -= w12;
  /* #130: output[0][8] = @32 */
  if (res[0]) res[0][8] = w32;
  /* #131: @13 = (@13*@9) */
  w13 *= w09;
  /* #132: @3 = (@3+@13) */
  w03 += w13;
  /* #133: @15 = (@15*@8) */
  w15 *= w08;
  /* #134: @3 = (@3-@15) */
  w03 -= w15;
  /* #135: @16 = (@16*@1) */
  w16 *= w01;
  /* #136: @3 = (@3+@16) */
  w03 += w16;
  /* #137: @17 = (@17*@2) */
  w17 *= w02;
  /* #138: @3 = (@3-@17) */
  w03 -= w17;
  /* #139: output[0][9] = @3 */
  if (res[0]) res[0][9] = w03;
  /* #140: @25 = zeros(3x1) */
  casadi_clear(w25, 3);
  /* #141: @27 = 
  [[1, 0, 0], 
   [0, 1, 0], 
   [0, 0, 1]] */
  wr27 = casadi_c0;
  /* #142: @14 = mac(@28,@23,@14) */
  for (i=0, rr=w14; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w28+j, ct=w23+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #143: @27 = (@27+@14) */
  for (i=0, rr=w27, cr=wr27, cs=w14; i<9; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #144: @23 = (@22*@23) */
  for (i=0, rr=w23, cs=w23; i<9; ++i) (*rr++)  = (w22*(*cs++));
  /* #145: @27 = (@27+@23) */
  for (i=0, rr=w27, cs=w23; i<9; ++i) (*rr++) += (*cs++);
  /* #146: @23 = @27' */
  for (i=0, rr=w23, cs=w27; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #147: @25 = mac(@23,@4,@25) */
  for (i=0, rr=w25; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w23+j, ct=w04+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #148: {NULL, NULL, @22} = vertsplit(@25) */
  w22 = w25[2];
  /* #149: output[0][10] = @22 */
  if (res[0]) res[0][10] = w22;
  /* #150: {@22, @3, @17} = vertsplit(@6) */
  w22 = w06[0];
  w03 = w06[1];
  w17 = w06[2];
  /* #151: output[0][11] = @22 */
  if (res[0]) res[0][11] = w22;
  /* #152: output[0][12] = @3 */
  if (res[0]) res[0][12] = w03;
  /* #153: output[0][13] = @17 */
  if (res[0]) res[0][13] = w17;
  /* #154: output[0][14] = @7 */
  if (res[0]) res[0][14] = w07;
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_mpcc_rate_mujoco_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Drone_ode_mpcc_rate_mujoco_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_mpcc_rate_mujoco_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_mpcc_rate_mujoco_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Drone_ode_mpcc_rate_mujoco_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_mpcc_rate_mujoco_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_mpcc_rate_mujoco_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_mpcc_rate_mujoco_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_mpcc_rate_mujoco_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_mpcc_rate_mujoco_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real Drone_ode_mpcc_rate_mujoco_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_mpcc_rate_mujoco_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_mpcc_rate_mujoco_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_mpcc_rate_mujoco_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_mpcc_rate_mujoco_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Drone_ode_mpcc_rate_mujoco_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8;
  if (sz_res) *sz_res = 8;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 123;
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_mpcc_rate_mujoco_expl_vde_adj_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 8*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 123*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
