/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) DQ_Drone_MPCC_runtime_accel_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_norm_2 CASADI_PREFIX(norm_2)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_norm_2(casadi_int n, const casadi_real* x) {
  return sqrt(casadi_dot(n, x, x));
}

static const casadi_int casadi_s0[3] = {16, 1, 1};
static const casadi_int casadi_s1[3] = {5, 1, 1};
static const casadi_int casadi_s2[3] = {18, 1, 1};
static const casadi_int casadi_s3[3] = {21, 1, 1};

static const casadi_real casadi_c0[9] = 
  {3.2085999999999998e-03, 0., 0., 0., 1.6731000000000001e-03, 0., 0., 0.,
  1.6730000000000000e-03};
static const casadi_real casadi_c1[3] = {3.1166240728043385e+02, 5.9769290538521307e+02, 5.9772863120143450e+02};

static const casadi_real casadi_zeros[16] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.};

/* DQ_Drone_MPCC_runtime_accel_expl_vde_adj:(i0[16],i1[16],i2[5],i3[18])->(o0[21]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *w00=w+8, *w01=w+24, *w02=w+28, *w03=w+44, *w04=w+52, w06, w07, *w08=w+60, *w09=w+63, w10, w11;
  casadi_real w12, w13, w14, w15, w16, w17, w18, w19, w20, w21, w22, w23;
  casadi_real w24, w25, *w26=w+83, *w27=w+87, *w28=w+91, *w29=w+107, *w30=w+123, *w31=w+127, *w32=w+131, w33, w34, *w35=w+137;
  casadi_real *w36=w+140, w37, w38, w39, w40, w41, w42, w43, w44, w45, w46, w47;
  casadi_real w48, w49, w50, *w51=w+158, w52, w53, w54, w55, w56, w57, w58, *w60=w+190;
  casadi_real *w61=w+199, *w62=w+202, w63, w64, w65, w66, w67, w68, w69, w70, w71, w72;
  casadi_real w73, *w74=w+216, *w75=w+280, *w76=w+288, *w77=w+352, *w78=w+384, *w79=w+416, w80, w81, w82, w83, w84;
  casadi_real w85, w86, w87, w88, w89, w90, *w91=w+459;
  const casadi_real *cs, *ct, *wr01, *wr02, *wr03, *wr04, *wr05, *wr59;
  /* #0: @0 = zeros(4x4) */
  casadi_clear(w00, 16);
  /* #1: @1 = zeros(4x1) */
  casadi_clear(w01, 4);
  /* #2: @2 = input[1][0] */
  wr02 = arg[1] ? arg[1] : casadi_zeros;
  /* #3: {@3, @4, @5, @6, @7} = vertsplit(@2) */
  wr03 = wr02;
  wr04 = wr02+8;
  wr05 = wr02+11;
  w06 = wr02[14];
  w07 = wr02[15];
  /* #4: @8 = (-@5) */
  for (i=0, rr=w08, cs=wr05; i<3; ++i) *rr++ = (- *cs++ );
  /* #5: @9 = @1; (@9[1:4] += @8) */
  casadi_copy(w01, 4, w09);
  for (rr=w09+1, cs=w08; rr!=w09+4; rr+=1) *rr += *cs++;
  /* #6: @10 = input[0][0] */
  w10 = arg[0] ? arg[0][0] : 0;
  /* #7: @11 = input[0][1] */
  w11 = arg[0] ? arg[0][1] : 0;
  /* #8: @12 = input[0][2] */
  w12 = arg[0] ? arg[0][2] : 0;
  /* #9: @13 = input[0][3] */
  w13 = arg[0] ? arg[0][3] : 0;
  /* #10: @14 = input[0][4] */
  w14 = arg[0] ? arg[0][4] : 0;
  /* #11: @15 = input[0][5] */
  w15 = arg[0] ? arg[0][5] : 0;
  /* #12: @16 = input[0][6] */
  w16 = arg[0] ? arg[0][6] : 0;
  /* #13: @17 = input[0][7] */
  w17 = arg[0] ? arg[0][7] : 0;
  /* #14: @18 = input[0][8] */
  w18 = arg[0] ? arg[0][8] : 0;
  /* #15: @19 = input[0][9] */
  w19 = arg[0] ? arg[0][9] : 0;
  /* #16: @20 = input[0][10] */
  w20 = arg[0] ? arg[0][10] : 0;
  /* #17: @21 = input[0][11] */
  w21 = arg[0] ? arg[0][11] : 0;
  /* #18: @22 = input[0][12] */
  w22 = arg[0] ? arg[0][12] : 0;
  /* #19: @23 = input[0][13] */
  w23 = arg[0] ? arg[0][13] : 0;
  /* #20: @24 = input[0][14] */
  w24 = arg[0] ? arg[0][14] : 0;
  /* #21: @25 = input[0][15] */
  w25 = arg[0] ? arg[0][15] : 0;
  /* #22: @2 = vertcat(@10, @11, @12, @13, @14, @15, @16, @17, @18, @19, @20, @21, @22, @23, @24, @25) */
  rr=w02;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w17;
  *rr++ = w18;
  *rr++ = w19;
  *rr++ = w20;
  *rr++ = w21;
  *rr++ = w22;
  *rr++ = w23;
  *rr++ = w24;
  *rr++ = w25;
  /* #23: @26 = @2[:4] */
  for (rr=w26, cs=w02+0; cs!=w02+4; cs+=1) *rr++ = *cs;
  /* #24: @27 = @26' */
  casadi_copy(w26, 4, w27);
  /* #25: @28 = mac(@9,@27,@0) */
  casadi_copy(w00, 16, w28);
  for (i=0, rr=w28; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, cs=w09+j, ct=w27+i*1; k<1; ++k) *rr += cs[k*4]**ct++;
  /* #26: @29 = @28' */
  for (i=0, rr=w29, cs=w28; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #27: {@27, @30, @31, @32} = horzsplit(@29) */
  casadi_copy(w29, 4, w27);
  casadi_copy(w29+4, 4, w30);
  casadi_copy(w29+8, 4, w31);
  casadi_copy(w29+12, 4, w32);
  /* #28: @32 = @32' */
  /* #29: {@24, @25, @33, @34} = horzsplit(@32) */
  w24 = w32[0];
  w25 = w32[1];
  w33 = w32[2];
  w34 = w32[3];
  /* #30: @32 = @1; (@32[0] += @34) */
  casadi_copy(w01, 4, w32);
  for (rr=w32+0, cs=(&w34); rr!=w32+1; rr+=1) *rr += *cs++;
  /* #31: (@32[1] += @33) */
  for (rr=w32+1, cs=(&w33); rr!=w32+2; rr+=1) *rr += *cs++;
  /* #32: @25 = (-@25) */
  w25 = (- w25 );
  /* #33: (@32[2] += @25) */
  for (rr=w32+2, cs=(&w25); rr!=w32+3; rr+=1) *rr += *cs++;
  /* #34: (@32[3] += @24) */
  for (rr=w32+3, cs=(&w24); rr!=w32+4; rr+=1) *rr += *cs++;
  /* #35: @31 = @31' */
  /* #36: {@24, @25, @33, @34} = horzsplit(@31) */
  w24 = w31[0];
  w25 = w31[1];
  w33 = w31[2];
  w34 = w31[3];
  /* #37: @34 = (-@34) */
  w34 = (- w34 );
  /* #38: (@32[1] += @34) */
  for (rr=w32+1, cs=(&w34); rr!=w32+2; rr+=1) *rr += *cs++;
  /* #39: (@32[0] += @33) */
  for (rr=w32+0, cs=(&w33); rr!=w32+1; rr+=1) *rr += *cs++;
  /* #40: (@32[3] += @25) */
  for (rr=w32+3, cs=(&w25); rr!=w32+4; rr+=1) *rr += *cs++;
  /* #41: (@32[2] += @24) */
  for (rr=w32+2, cs=(&w24); rr!=w32+3; rr+=1) *rr += *cs++;
  /* #42: @30 = @30' */
  /* #43: {@24, @25, @33, @34} = horzsplit(@30) */
  w24 = w30[0];
  w25 = w30[1];
  w33 = w30[2];
  w34 = w30[3];
  /* #44: (@32[2] += @34) */
  for (rr=w32+2, cs=(&w34); rr!=w32+3; rr+=1) *rr += *cs++;
  /* #45: @33 = (-@33) */
  w33 = (- w33 );
  /* #46: (@32[3] += @33) */
  for (rr=w32+3, cs=(&w33); rr!=w32+4; rr+=1) *rr += *cs++;
  /* #47: (@32[0] += @25) */
  for (rr=w32+0, cs=(&w25); rr!=w32+1; rr+=1) *rr += *cs++;
  /* #48: (@32[1] += @24) */
  for (rr=w32+1, cs=(&w24); rr!=w32+2; rr+=1) *rr += *cs++;
  /* #49: @27 = @27' */
  /* #50: {@24, @25, @33, @34} = horzsplit(@27) */
  w24 = w27[0];
  w25 = w27[1];
  w33 = w27[2];
  w34 = w27[3];
  /* #51: @34 = (-@34) */
  w34 = (- w34 );
  /* #52: (@32[3] += @34) */
  for (rr=w32+3, cs=(&w34); rr!=w32+4; rr+=1) *rr += *cs++;
  /* #53: @33 = (-@33) */
  w33 = (- w33 );
  /* #54: (@32[2] += @33) */
  for (rr=w32+2, cs=(&w33); rr!=w32+3; rr+=1) *rr += *cs++;
  /* #55: @25 = (-@25) */
  w25 = (- w25 );
  /* #56: (@32[1] += @25) */
  for (rr=w32+1, cs=(&w25); rr!=w32+2; rr+=1) *rr += *cs++;
  /* #57: (@32[0] += @24) */
  for (rr=w32+0, cs=(&w24); rr!=w32+1; rr+=1) *rr += *cs++;
  /* #58: @24 = 0 */
  w24 = 0.;
  /* #59: @25 = 9.81 */
  w25 = 9.8100000000000005e+00;
  /* #60: @33 = 1 */
  w33 = 1.;
  /* #61: @8 = vertcat(@24, @24, @33) */
  rr=w08;
  *rr++ = w24;
  *rr++ = w24;
  *rr++ = w33;
  /* #62: @35 = (@25*@8) */
  for (i=0, rr=w35, cs=w08; i<3; ++i) (*rr++)  = (w25*(*cs++));
  /* #63: @27 = vertcat(@24, @35) */
  rr=w27;
  *rr++ = w24;
  for (i=0, cs=w35; i<3; ++i) *rr++ = *cs++;
  /* #64: @30 = @27' */
  casadi_copy(w27, 4, w30);
  /* #65: @29 = mac(@32,@30,@0) */
  casadi_copy(w00, 16, w29);
  for (i=0, rr=w29; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, cs=w32+j, ct=w30+i*1; k<1; ++k) *rr += cs[k*4]**ct++;
  /* #66: @28 = @29' */
  for (i=0, rr=w28, cs=w29; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #67: {@32, @30, @31, @36} = horzsplit(@28) */
  casadi_copy(w28, 4, w32);
  casadi_copy(w28+4, 4, w30);
  casadi_copy(w28+8, 4, w31);
  casadi_copy(w28+12, 4, w36);
  /* #68: @36 = @36' */
  /* #69: {@25, @34, @37, @38} = horzsplit(@36) */
  w25 = w36[0];
  w34 = w36[1];
  w37 = w36[2];
  w38 = w36[3];
  /* #70: @31 = @31' */
  /* #71: {@39, @40, @41, @42} = horzsplit(@31) */
  w39 = w31[0];
  w40 = w31[1];
  w41 = w31[2];
  w42 = w31[3];
  /* #72: @38 = (@38+@41) */
  w38 += w41;
  /* #73: @30 = @30' */
  /* #74: {@41, @43, @44, @45} = horzsplit(@30) */
  w41 = w30[0];
  w43 = w30[1];
  w44 = w30[2];
  w45 = w30[3];
  /* #75: @38 = (@38+@43) */
  w38 += w43;
  /* #76: @32 = @32' */
  /* #77: {@43, @46, @47, @48} = horzsplit(@32) */
  w43 = w32[0];
  w46 = w32[1];
  w47 = w32[2];
  w48 = w32[3];
  /* #78: @38 = (@38+@43) */
  w38 += w43;
  /* #79: @28 = zeros(16x1) */
  casadi_clear(w28, 16);
  /* #80: @32 = horzcat(@10, @11, @12, @13) */
  rr=w32;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  /* #81: @32 = @32' */
  /* #82: @43 = (-@11) */
  w43 = (- w11 );
  /* #83: @49 = (-@12) */
  w49 = (- w12 );
  /* #84: @30 = horzcat(@43, @10, @13, @49) */
  rr=w30;
  *rr++ = w43;
  *rr++ = w10;
  *rr++ = w13;
  *rr++ = w49;
  /* #85: @30 = @30' */
  /* #86: @50 = (-@13) */
  w50 = (- w13 );
  /* #87: @31 = horzcat(@49, @50, @10, @11) */
  rr=w31;
  *rr++ = w49;
  *rr++ = w50;
  *rr++ = w10;
  *rr++ = w11;
  /* #88: @31 = @31' */
  /* #89: @36 = horzcat(@50, @12, @43, @10) */
  rr=w36;
  *rr++ = w50;
  *rr++ = w12;
  *rr++ = w43;
  *rr++ = w10;
  /* #90: @36 = @36' */
  /* #91: @29 = horzcat(@32, @30, @31, @36) */
  rr=w29;
  for (i=0, cs=w32; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w30; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w31; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w36; i<4; ++i) *rr++ = *cs++;
  /* #92: @51 = @29' */
  for (i=0, rr=w51, cs=w29; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #93: @32 = mac(@51,@27,@1) */
  casadi_copy(w01, 4, w32);
  for (i=0, rr=w32; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, cs=w51+j, ct=w27+i*4; k<4; ++k) *rr += cs[k*4]**ct++;
  /* #94: @52 = @32[0] */
  for (rr=(&w52), cs=w32+0; cs!=w32+1; cs+=1) *rr++ = *cs;
  /* #95: @53 = @32[1] */
  for (rr=(&w53), cs=w32+1; cs!=w32+2; cs+=1) *rr++ = *cs;
  /* #96: @54 = (-@53) */
  w54 = (- w53 );
  /* #97: @55 = @32[2] */
  for (rr=(&w55), cs=w32+2; cs!=w32+3; cs+=1) *rr++ = *cs;
  /* #98: @56 = (-@55) */
  w56 = (- w55 );
  /* #99: @57 = @32[3] */
  for (rr=(&w57), cs=w32+3; cs!=w32+4; cs+=1) *rr++ = *cs;
  /* #100: @58 = (-@57) */
  w58 = (- w57 );
  /* #101: @32 = horzcat(@52, @54, @56, @58) */
  rr=w32;
  *rr++ = w52;
  *rr++ = w54;
  *rr++ = w56;
  *rr++ = w58;
  /* #102: @32 = @32' */
  /* #103: @27 = horzcat(@53, @52, @58, @55) */
  rr=w27;
  *rr++ = w53;
  *rr++ = w52;
  *rr++ = w58;
  *rr++ = w55;
  /* #104: @27 = @27' */
  /* #105: @30 = horzcat(@55, @57, @52, @54) */
  rr=w30;
  *rr++ = w55;
  *rr++ = w57;
  *rr++ = w52;
  *rr++ = w54;
  /* #106: @30 = @30' */
  /* #107: @31 = horzcat(@57, @56, @53, @52) */
  rr=w31;
  *rr++ = w57;
  *rr++ = w56;
  *rr++ = w53;
  *rr++ = w52;
  /* #108: @31 = @31' */
  /* #109: @51 = horzcat(@32, @27, @30, @31) */
  rr=w51;
  for (i=0, cs=w32; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w27; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w30; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w31; i<4; ++i) *rr++ = *cs++;
  /* #110: @1 = mac(@51,@9,@1) */
  for (i=0, rr=w01; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, cs=w51+j, ct=w09+i*4; k<4; ++k) *rr += cs[k*4]**ct++;
  /* #111: (@28[:4] += @1) */
  for (rr=w28+0, cs=w01; rr!=w28+4; rr+=1) *rr += *cs++;
  /* #112: @35 = zeros(3x1) */
  casadi_clear(w35, 3);
  /* #113: @59 = 
  [[0.0032086, 0, 0], 
   [0, 0.0016731, 0], 
   [0, 0, 0.001673]] */
  wr59 = casadi_c0;
  /* #114: @60 = @59' */
  for (i=0, rr=w60, cs=wr59; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #115: @61 = 
  [[311.662, 00, 00], 
   [00, 597.693, 00], 
   [00, 00, 597.729]] */
  casadi_copy(casadi_c1, 3, w61);
  /* #116: @61 = nonzeros(@61) */
  /* #117: @61 = (@61*@4) */
  for (i=0, rr=w61, cs=wr04; i<3; ++i) (*rr++) *= (*cs++);
  /* #118: @4 = (-@61) */
  for (i=0, rr=w04, cs=w61; i<3; ++i) *rr++ = (- *cs++ );
  /* #119: {@57, @56, @53} = vertsplit(@4) */
  w57 = w04[0];
  w56 = w04[1];
  w53 = w04[2];
  /* #120: @52 = (@20*@56) */
  w52  = (w20*w56);
  /* #121: @55 = (@19*@53) */
  w55  = (w19*w53);
  /* #122: @52 = (@52-@55) */
  w52 -= w55;
  /* #123: @4 = @35; (@4[0] += @52) */
  casadi_copy(w35, 3, w04);
  for (rr=w04+0, cs=(&w52); rr!=w04+1; rr+=1) *rr += *cs++;
  /* #124: @52 = (@18*@53) */
  w52  = (w18*w53);
  /* #125: @55 = (@20*@57) */
  w55  = (w20*w57);
  /* #126: @52 = (@52-@55) */
  w52 -= w55;
  /* #127: (@4[1] += @52) */
  for (rr=w04+1, cs=(&w52); rr!=w04+2; rr+=1) *rr += *cs++;
  /* #128: @52 = (@19*@57) */
  w52  = (w19*w57);
  /* #129: @55 = (@18*@56) */
  w55  = (w18*w56);
  /* #130: @52 = (@52-@55) */
  w52 -= w55;
  /* #131: (@4[2] += @52) */
  for (rr=w04+2, cs=(&w52); rr!=w04+3; rr+=1) *rr += *cs++;
  /* #132: @62 = mac(@60,@4,@35) */
  casadi_copy(w35, 3, w62);
  for (i=0, rr=w62; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w60+j, ct=w04+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #133: (@28[8:11] += @62) */
  for (rr=w28+8, cs=w62; rr!=w28+11; rr+=1) *rr += *cs++;
  /* #134: @52 = 10 */
  w52 = 10.;
  /* #135: @55 = ||@26||_F */
  w55 = casadi_norm_2(4, w26);
  /* #136: @33 = (@33-@55) */
  w33 -= w55;
  /* #137: @33 = (@52*@33) */
  w33  = (w52*w33);
  /* #138: {@1, NULL} = vertsplit(@3) */
  wr01 = wr03;
  /* #139: @9 = (@33*@1) */
  for (i=0, rr=w09, cs=wr01; i<4; ++i) (*rr++)  = (w33*(*cs++));
  /* #140: @33 = dot(@26, @1) */
  w33 = casadi_dot(4, w26, wr01);
  /* #141: @52 = (@52*@33) */
  w52 *= w33;
  /* #142: @52 = (@52/@55) */
  w52 /= w55;
  /* #143: @26 = (@52*@26) */
  for (i=0, rr=w26, cs=w26; i<4; ++i) (*rr++)  = (w52*(*cs++));
  /* #144: @9 = (@9-@26) */
  for (i=0, rr=w09, cs=w26; i<4; ++i) (*rr++) -= (*cs++);
  /* #145: (@28[:4] += @9) */
  for (rr=w28+0, cs=w09; rr!=w28+4; rr+=1) *rr += *cs++;
  /* #146: {@52, @55, @33, @54, @58, @63, @64, @65, @66, @67, @68, @69, @70, @71, @72, @73} = vertsplit(@28) */
  w52 = w28[0];
  w55 = w28[1];
  w33 = w28[2];
  w54 = w28[3];
  w58 = w28[4];
  w63 = w28[5];
  w64 = w28[6];
  w65 = w28[7];
  w66 = w28[8];
  w67 = w28[9];
  w68 = w28[10];
  w69 = w28[11];
  w70 = w28[12];
  w71 = w28[13];
  w72 = w28[14];
  w73 = w28[15];
  /* #147: @38 = (@38+@52) */
  w38 += w52;
  /* #148: @74 = zeros(8x8) */
  casadi_clear(w74, 64);
  /* #149: @52 = 0.5 */
  w52 = 5.0000000000000000e-01;
  /* #150: @3 = (@52*@3) */
  for (i=0, rr=w03, cs=wr03; i<8; ++i) (*rr++)  = (w52*(*cs++));
  /* #151: @75 = vertcat(@24, @18, @19, @20, @24, @21, @22, @23) */
  rr=w75;
  *rr++ = w24;
  *rr++ = w18;
  *rr++ = w19;
  *rr++ = w20;
  *rr++ = w24;
  *rr++ = w21;
  *rr++ = w22;
  *rr++ = w23;
  /* #152: @75 = @75' */
  /* #153: @74 = mac(@3,@75,@74) */
  for (i=0, rr=w74; i<8; ++i) for (j=0; j<8; ++j, ++rr) for (k=0, cs=w03+j, ct=w75+i*1; k<1; ++k) *rr += cs[k*8]**ct++;
  /* #154: @76 = @74' */
  for (i=0, rr=w76, cs=w74; i<8; ++i) for (j=0; j<8; ++j) rr[i+j*8] = *cs++;
  /* #155: {@77, @78} = horzsplit(@76) */
  casadi_copy(w76, 32, w77);
  casadi_copy(w76+32, 32, w78);
  /* #156: @79 = @78' */
  for (i=0, rr=w79, cs=w78; i<4; ++i) for (j=0; j<8; ++j) rr[i+j*4] = *cs++;
  /* #157: {@28, @51} = horzsplit(@79) */
  casadi_copy(w79, 16, w28);
  casadi_copy(w79+16, 16, w51);
  /* #158: @79 = @77' */
  for (i=0, rr=w79, cs=w77; i<4; ++i) for (j=0; j<8; ++j) rr[i+j*4] = *cs++;
  /* #159: {@29, NULL} = horzsplit(@79) */
  casadi_copy(w79, 16, w29);
  /* #160: @51 = (@51+@29) */
  for (i=0, rr=w51, cs=w29; i<16; ++i) (*rr++) += (*cs++);
  /* #161: @29 = @51' */
  for (i=0, rr=w29, cs=w51; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #162: {@9, @26, @1, @32} = horzsplit(@29) */
  casadi_copy(w29, 4, w09);
  casadi_copy(w29+4, 4, w26);
  casadi_copy(w29+8, 4, w01);
  casadi_copy(w29+12, 4, w32);
  /* #163: @32 = @32' */
  /* #164: {@24, @52, @80, @81} = horzsplit(@32) */
  w24 = w32[0];
  w52 = w32[1];
  w80 = w32[2];
  w81 = w32[3];
  /* #165: @38 = (@38+@81) */
  w38 += w81;
  /* #166: @1 = @1' */
  /* #167: {@81, @82, @83, @84} = horzsplit(@1) */
  w81 = w01[0];
  w82 = w01[1];
  w83 = w01[2];
  w84 = w01[3];
  /* #168: @38 = (@38+@83) */
  w38 += w83;
  /* #169: @26 = @26' */
  /* #170: {@83, @85, @86, @87} = horzsplit(@26) */
  w83 = w26[0];
  w85 = w26[1];
  w86 = w26[2];
  w87 = w26[3];
  /* #171: @38 = (@38+@85) */
  w38 += w85;
  /* #172: @9 = @9' */
  /* #173: {@85, @88, @89, @90} = horzsplit(@9) */
  w85 = w09[0];
  w88 = w09[1];
  w89 = w09[2];
  w90 = w09[3];
  /* #174: @38 = (@38+@85) */
  w38 += w85;
  /* #175: output[0][0] = @38 */
  if (res[0]) res[0][0] = w38;
  /* #176: @37 = (@37+@41) */
  w37 += w41;
  /* #177: @42 = (@42-@37) */
  w42 -= w37;
  /* #178: @42 = (@42+@46) */
  w42 += w46;
  /* #179: @42 = (@42+@55) */
  w42 += w55;
  /* #180: @42 = (@42+@80) */
  w42 += w80;
  /* #181: @42 = (@42-@84) */
  w42 -= w84;
  /* #182: @42 = (@42+@83) */
  w42 += w83;
  /* #183: @42 = (@42-@88) */
  w42 -= w88;
  /* #184: output[0][1] = @42 */
  if (res[0]) res[0][1] = w42;
  /* #185: @39 = (@39+@45) */
  w39 += w45;
  /* #186: @34 = (@34-@39) */
  w34 -= w39;
  /* #187: @34 = (@34+@47) */
  w34 += w47;
  /* #188: @34 = (@34+@33) */
  w34 += w33;
  /* #189: @34 = (@34-@52) */
  w34 -= w52;
  /* #190: @34 = (@34+@81) */
  w34 += w81;
  /* #191: @34 = (@34+@87) */
  w34 += w87;
  /* #192: @34 = (@34-@89) */
  w34 -= w89;
  /* #193: output[0][2] = @34 */
  if (res[0]) res[0][2] = w34;
  /* #194: @25 = (@25+@40) */
  w25 += w40;
  /* #195: @44 = (@44-@25) */
  w44 -= w25;
  /* #196: @44 = (@44+@48) */
  w44 += w48;
  /* #197: @44 = (@44+@54) */
  w44 += w54;
  /* #198: @44 = (@44+@24) */
  w44 += w24;
  /* #199: @44 = (@44+@82) */
  w44 += w82;
  /* #200: @44 = (@44-@86) */
  w44 -= w86;
  /* #201: @44 = (@44-@90) */
  w44 -= w90;
  /* #202: output[0][3] = @44 */
  if (res[0]) res[0][3] = w44;
  /* #203: @29 = @28' */
  for (i=0, rr=w29, cs=w28; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #204: {@9, @26, @1, @32} = horzsplit(@29) */
  casadi_copy(w29, 4, w09);
  casadi_copy(w29+4, 4, w26);
  casadi_copy(w29+8, 4, w01);
  casadi_copy(w29+12, 4, w32);
  /* #205: @32 = @32' */
  /* #206: {@44, @90, @86, @82} = horzsplit(@32) */
  w44 = w32[0];
  w90 = w32[1];
  w86 = w32[2];
  w82 = w32[3];
  /* #207: @58 = (@58+@82) */
  w58 += w82;
  /* #208: @1 = @1' */
  /* #209: {@82, @24, @54, @48} = horzsplit(@1) */
  w82 = w01[0];
  w24 = w01[1];
  w54 = w01[2];
  w48 = w01[3];
  /* #210: @58 = (@58+@54) */
  w58 += w54;
  /* #211: @26 = @26' */
  /* #212: {@54, @25, @40, @34} = horzsplit(@26) */
  w54 = w26[0];
  w25 = w26[1];
  w40 = w26[2];
  w34 = w26[3];
  /* #213: @58 = (@58+@25) */
  w58 += w25;
  /* #214: @9 = @9' */
  /* #215: {@25, @89, @87, @81} = horzsplit(@9) */
  w25 = w09[0];
  w89 = w09[1];
  w87 = w09[2];
  w81 = w09[3];
  /* #216: @58 = (@58+@25) */
  w58 += w25;
  /* #217: output[0][4] = @58 */
  if (res[0]) res[0][4] = w58;
  /* #218: @63 = (@63+@86) */
  w63 += w86;
  /* #219: @63 = (@63-@48) */
  w63 -= w48;
  /* #220: @63 = (@63+@54) */
  w63 += w54;
  /* #221: @63 = (@63-@89) */
  w63 -= w89;
  /* #222: output[0][5] = @63 */
  if (res[0]) res[0][5] = w63;
  /* #223: @64 = (@64-@90) */
  w64 -= w90;
  /* #224: @64 = (@64+@82) */
  w64 += w82;
  /* #225: @64 = (@64+@34) */
  w64 += w34;
  /* #226: @64 = (@64-@87) */
  w64 -= w87;
  /* #227: output[0][6] = @64 */
  if (res[0]) res[0][6] = w64;
  /* #228: @65 = (@65+@44) */
  w65 += w44;
  /* #229: @65 = (@65+@24) */
  w65 += w24;
  /* #230: @65 = (@65-@40) */
  w65 -= w40;
  /* #231: @65 = (@65-@81) */
  w65 -= w81;
  /* #232: output[0][7] = @65 */
  if (res[0]) res[0][7] = w65;
  /* #233: {@65, @81, @40} = vertsplit(@5) */
  w65 = wr05[0];
  w81 = wr05[1];
  w40 = wr05[2];
  /* #234: @24 = (@23*@81) */
  w24  = (w23*w81);
  /* #235: @44 = (@22*@40) */
  w44  = (w22*w40);
  /* #236: @24 = (@24-@44) */
  w24 -= w44;
  /* #237: @62 = @2[8:11] */
  for (rr=w62, cs=w02+8; cs!=w02+11; cs+=1) *rr++ = *cs;
  /* #238: @35 = mac(@59,@62,@35) */
  for (i=0, rr=w35; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=wr59+j, ct=w62+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #239: @44 = @35[1] */
  for (rr=(&w44), cs=w35+1; cs!=w35+2; cs+=1) *rr++ = *cs;
  /* #240: @64 = (@44*@53) */
  w64  = (w44*w53);
  /* #241: @24 = (@24+@64) */
  w24 += w64;
  /* #242: @64 = @35[2] */
  for (rr=(&w64), cs=w35+2; cs!=w35+3; cs+=1) *rr++ = *cs;
  /* #243: @87 = (@64*@56) */
  w87  = (w64*w56);
  /* #244: @24 = (@24-@87) */
  w24 -= w87;
  /* #245: @24 = (@24+@66) */
  w24 += w66;
  /* #246: @75 = zeros(8x1) */
  casadi_clear(w75, 8);
  /* #247: @9 = horzcat(@10, @43, @49, @50) */
  rr=w09;
  *rr++ = w10;
  *rr++ = w43;
  *rr++ = w49;
  *rr++ = w50;
  /* #248: @9 = @9' */
  /* #249: @26 = horzcat(@11, @10, @50, @12) */
  rr=w26;
  *rr++ = w11;
  *rr++ = w10;
  *rr++ = w50;
  *rr++ = w12;
  /* #250: @26 = @26' */
  /* #251: @1 = horzcat(@12, @13, @10, @43) */
  rr=w01;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w10;
  *rr++ = w43;
  /* #252: @1 = @1' */
  /* #253: @32 = horzcat(@13, @49, @11, @10) */
  rr=w32;
  *rr++ = w13;
  *rr++ = w49;
  *rr++ = w11;
  *rr++ = w10;
  /* #254: @32 = @32' */
  /* #255: @2 = horzcat(@9, @26, @1, @32) */
  rr=w02;
  for (i=0, cs=w09; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w26; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w01; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w32; i<4; ++i) *rr++ = *cs++;
  /* #256: @29 = @2' */
  for (i=0, rr=w29, cs=w02; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #257: @79 = horzcat(@29, @0) */
  rr=w79;
  for (i=0, cs=w29; i<16; ++i) *rr++ = *cs++;
  for (i=0, cs=w00; i<16; ++i) *rr++ = *cs++;
  /* #258: @77 = @79' */
  for (i=0, rr=w77, cs=w79; i<8; ++i) for (j=0; j<4; ++j) rr[i+j*8] = *cs++;
  /* #259: @13 = (-@15) */
  w13 = (- w15 );
  /* #260: @49 = (-@16) */
  w49 = (- w16 );
  /* #261: @11 = (-@17) */
  w11 = (- w17 );
  /* #262: @9 = horzcat(@14, @13, @49, @11) */
  rr=w09;
  *rr++ = w14;
  *rr++ = w13;
  *rr++ = w49;
  *rr++ = w11;
  /* #263: @9 = @9' */
  /* #264: @26 = horzcat(@15, @14, @11, @16) */
  rr=w26;
  *rr++ = w15;
  *rr++ = w14;
  *rr++ = w11;
  *rr++ = w16;
  /* #265: @26 = @26' */
  /* #266: @1 = horzcat(@16, @17, @14, @13) */
  rr=w01;
  *rr++ = w16;
  *rr++ = w17;
  *rr++ = w14;
  *rr++ = w13;
  /* #267: @1 = @1' */
  /* #268: @32 = horzcat(@17, @49, @15, @14) */
  rr=w32;
  *rr++ = w17;
  *rr++ = w49;
  *rr++ = w15;
  *rr++ = w14;
  /* #269: @32 = @32' */
  /* #270: @0 = horzcat(@9, @26, @1, @32) */
  rr=w00;
  for (i=0, cs=w09; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w26; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w01; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w32; i<4; ++i) *rr++ = *cs++;
  /* #271: @2 = @0' */
  for (i=0, rr=w02, cs=w00; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #272: @79 = horzcat(@2, @29) */
  rr=w79;
  for (i=0, cs=w02; i<16; ++i) *rr++ = *cs++;
  for (i=0, cs=w29; i<16; ++i) *rr++ = *cs++;
  /* #273: @78 = @79' */
  for (i=0, rr=w78, cs=w79; i<8; ++i) for (j=0; j<4; ++j) rr[i+j*8] = *cs++;
  /* #274: @76 = horzcat(@77, @78) */
  rr=w76;
  for (i=0, cs=w77; i<32; ++i) *rr++ = *cs++;
  for (i=0, cs=w78; i<32; ++i) *rr++ = *cs++;
  /* #275: @75 = mac(@76,@3,@75) */
  for (i=0, rr=w75; i<1; ++i) for (j=0; j<8; ++j, ++rr) for (k=0, cs=w76+j, ct=w03+i*8; k<8; ++k) *rr += cs[k*8]**ct++;
  /* #276: {NULL, @17, @49, @15, NULL, @14, @16, @13} = vertsplit(@75) */
  w17 = w75[1];
  w49 = w75[2];
  w15 = w75[3];
  w14 = w75[5];
  w16 = w75[6];
  w13 = w75[7];
  /* #277: @24 = (@24+@17) */
  w24 += w17;
  /* #278: output[0][8] = @24 */
  if (res[0]) res[0][8] = w24;
  /* #279: @24 = (@21*@40) */
  w24  = (w21*w40);
  /* #280: @23 = (@23*@65) */
  w23 *= w65;
  /* #281: @24 = (@24-@23) */
  w24 -= w23;
  /* #282: @23 = @35[0] */
  for (rr=(&w23), cs=w35+0; cs!=w35+1; cs+=1) *rr++ = *cs;
  /* #283: @53 = (@23*@53) */
  w53  = (w23*w53);
  /* #284: @24 = (@24-@53) */
  w24 -= w53;
  /* #285: @64 = (@64*@57) */
  w64 *= w57;
  /* #286: @24 = (@24+@64) */
  w24 += w64;
  /* #287: @24 = (@24+@67) */
  w24 += w67;
  /* #288: @24 = (@24+@49) */
  w24 += w49;
  /* #289: output[0][9] = @24 */
  if (res[0]) res[0][9] = w24;
  /* #290: @22 = (@22*@65) */
  w22 *= w65;
  /* #291: @21 = (@21*@81) */
  w21 *= w81;
  /* #292: @22 = (@22-@21) */
  w22 -= w21;
  /* #293: @23 = (@23*@56) */
  w23 *= w56;
  /* #294: @22 = (@22+@23) */
  w22 += w23;
  /* #295: @44 = (@44*@57) */
  w44 *= w57;
  /* #296: @22 = (@22-@44) */
  w22 -= w44;
  /* #297: @22 = (@22+@68) */
  w22 += w68;
  /* #298: @22 = (@22+@15) */
  w22 += w15;
  /* #299: output[0][10] = @22 */
  if (res[0]) res[0][10] = w22;
  /* #300: @22 = (@19*@40) */
  w22  = (w19*w40);
  /* #301: @15 = (@20*@81) */
  w15  = (w20*w81);
  /* #302: @22 = (@22-@15) */
  w22 -= w15;
  /* #303: @22 = (@22+@69) */
  w22 += w69;
  /* #304: @22 = (@22+@14) */
  w22 += w14;
  /* #305: output[0][11] = @22 */
  if (res[0]) res[0][11] = w22;
  /* #306: @20 = (@20*@65) */
  w20 *= w65;
  /* #307: @40 = (@18*@40) */
  w40  = (w18*w40);
  /* #308: @20 = (@20-@40) */
  w20 -= w40;
  /* #309: @20 = (@20+@70) */
  w20 += w70;
  /* #310: @20 = (@20+@16) */
  w20 += w16;
  /* #311: output[0][12] = @20 */
  if (res[0]) res[0][12] = w20;
  /* #312: @18 = (@18*@81) */
  w18 *= w81;
  /* #313: @19 = (@19*@65) */
  w19 *= w65;
  /* #314: @18 = (@18-@19) */
  w18 -= w19;
  /* #315: @18 = (@18+@71) */
  w18 += w71;
  /* #316: @18 = (@18+@13) */
  w18 += w13;
  /* #317: output[0][13] = @18 */
  if (res[0]) res[0][13] = w18;
  /* #318: output[0][14] = @72 */
  if (res[0]) res[0][14] = w72;
  /* #319: @6 = (@6+@73) */
  w06 += w73;
  /* #320: output[0][15] = @6 */
  if (res[0]) res[0][15] = w06;
  /* #321: @6 = 0.963391 */
  w06 = 9.6339113680154143e-01;
  /* #322: @73 = dot(@8, @5) */
  w73 = casadi_dot(3, w08, wr05);
  /* #323: @6 = (@6*@73) */
  w06 *= w73;
  /* #324: @91 = zeros(5x1) */
  casadi_clear(w91, 5);
  /* #325: (@91[1:4] += @61) */
  for (rr=w91+1, cs=w61; rr!=w91+4; rr+=1) *rr += *cs++;
  /* #326: {@73, @72, @18, @13, @71} = vertsplit(@91) */
  w73 = w91[0];
  w72 = w91[1];
  w18 = w91[2];
  w13 = w91[3];
  w71 = w91[4];
  /* #327: @6 = (@6+@73) */
  w06 += w73;
  /* #328: output[0][16] = @6 */
  if (res[0]) res[0][16] = w06;
  /* #329: output[0][17] = @72 */
  if (res[0]) res[0][17] = w72;
  /* #330: output[0][18] = @18 */
  if (res[0]) res[0][18] = w18;
  /* #331: output[0][19] = @13 */
  if (res[0]) res[0][19] = w13;
  /* #332: @7 = (@7+@71) */
  w07 += w71;
  /* #333: output[0][20] = @7 */
  if (res[0]) res[0][20] = w07;
  return 0;
}

CASADI_SYMBOL_EXPORT int DQ_Drone_MPCC_runtime_accel_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int DQ_Drone_MPCC_runtime_accel_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int DQ_Drone_MPCC_runtime_accel_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void DQ_Drone_MPCC_runtime_accel_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int DQ_Drone_MPCC_runtime_accel_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void DQ_Drone_MPCC_runtime_accel_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void DQ_Drone_MPCC_runtime_accel_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void DQ_Drone_MPCC_runtime_accel_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int DQ_Drone_MPCC_runtime_accel_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int DQ_Drone_MPCC_runtime_accel_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real DQ_Drone_MPCC_runtime_accel_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* DQ_Drone_MPCC_runtime_accel_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* DQ_Drone_MPCC_runtime_accel_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* DQ_Drone_MPCC_runtime_accel_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* DQ_Drone_MPCC_runtime_accel_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int DQ_Drone_MPCC_runtime_accel_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 20;
  if (sz_res) *sz_res = 17;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 464;
  return 0;
}

CASADI_SYMBOL_EXPORT int DQ_Drone_MPCC_runtime_accel_expl_vde_adj_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 20*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 17*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 464*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
