/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) DQ_Drone_MPCC_runtime_accel_constr_h_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_norm_2 CASADI_PREFIX(norm_2)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_norm_2(casadi_int n, const casadi_real* x) {
  return sqrt(casadi_dot(n, x, x));
}

static const casadi_int casadi_s0[3] = {16, 1, 1};
static const casadi_int casadi_s1[3] = {5, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {18, 1, 1};
static const casadi_int casadi_s4[3] = {1, 1, 1};

/* DQ_Drone_MPCC_runtime_accel_constr_h_fun:(i0[16],i1[5],i2[0],i3[18])->(o0) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, w00, w01, w02, w03, w04, w05, w06, w07, w08, w09, w10;
  casadi_real w11, w12, w13, w14, w15, *w16=w+16, *w17=w+32;
  const casadi_real *cs;
  /* #0: @0 = input[0][0] */
  w00 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = input[0][1] */
  w01 = arg[0] ? arg[0][1] : 0;
  /* #2: @2 = input[0][2] */
  w02 = arg[0] ? arg[0][2] : 0;
  /* #3: @3 = input[0][3] */
  w03 = arg[0] ? arg[0][3] : 0;
  /* #4: @4 = input[0][4] */
  w04 = arg[0] ? arg[0][4] : 0;
  /* #5: @5 = input[0][5] */
  w05 = arg[0] ? arg[0][5] : 0;
  /* #6: @6 = input[0][6] */
  w06 = arg[0] ? arg[0][6] : 0;
  /* #7: @7 = input[0][7] */
  w07 = arg[0] ? arg[0][7] : 0;
  /* #8: @8 = input[0][8] */
  w08 = arg[0] ? arg[0][8] : 0;
  /* #9: @9 = input[0][9] */
  w09 = arg[0] ? arg[0][9] : 0;
  /* #10: @10 = input[0][10] */
  w10 = arg[0] ? arg[0][10] : 0;
  /* #11: @11 = input[0][11] */
  w11 = arg[0] ? arg[0][11] : 0;
  /* #12: @12 = input[0][12] */
  w12 = arg[0] ? arg[0][12] : 0;
  /* #13: @13 = input[0][13] */
  w13 = arg[0] ? arg[0][13] : 0;
  /* #14: @14 = input[0][14] */
  w14 = arg[0] ? arg[0][14] : 0;
  /* #15: @15 = input[0][15] */
  w15 = arg[0] ? arg[0][15] : 0;
  /* #16: @16 = vertcat(@0, @1, @2, @3, @4, @5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15) */
  rr=w16;
  *rr++ = w00;
  *rr++ = w01;
  *rr++ = w02;
  *rr++ = w03;
  *rr++ = w04;
  *rr++ = w05;
  *rr++ = w06;
  *rr++ = w07;
  *rr++ = w08;
  *rr++ = w09;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  /* #17: @17 = @16[:4] */
  for (rr=w17, cs=w16+0; cs!=w16+4; cs+=1) *rr++ = *cs;
  /* #18: @0 = ||@17||_F */
  w00 = casadi_norm_2(4, w17);
  /* #19: output[0][0] = @0 */
  if (res[0]) res[0][0] = w00;
  return 0;
}

CASADI_SYMBOL_EXPORT int DQ_Drone_MPCC_runtime_accel_constr_h_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int DQ_Drone_MPCC_runtime_accel_constr_h_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int DQ_Drone_MPCC_runtime_accel_constr_h_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void DQ_Drone_MPCC_runtime_accel_constr_h_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int DQ_Drone_MPCC_runtime_accel_constr_h_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void DQ_Drone_MPCC_runtime_accel_constr_h_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void DQ_Drone_MPCC_runtime_accel_constr_h_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void DQ_Drone_MPCC_runtime_accel_constr_h_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int DQ_Drone_MPCC_runtime_accel_constr_h_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int DQ_Drone_MPCC_runtime_accel_constr_h_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real DQ_Drone_MPCC_runtime_accel_constr_h_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* DQ_Drone_MPCC_runtime_accel_constr_h_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* DQ_Drone_MPCC_runtime_accel_constr_h_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* DQ_Drone_MPCC_runtime_accel_constr_h_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* DQ_Drone_MPCC_runtime_accel_constr_h_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int DQ_Drone_MPCC_runtime_accel_constr_h_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 20;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 36;
  return 0;
}

CASADI_SYMBOL_EXPORT int DQ_Drone_MPCC_runtime_accel_constr_h_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 20*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 36*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
