/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Drone_ode_mpcc_rate_mil_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_norm_2 CASADI_PREFIX(norm_2)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_norm_2(casadi_int n, const casadi_real* x) {
  return sqrt(casadi_dot(n, x, x));
}

static const casadi_int casadi_s0[3] = {14, 1, 1};
static const casadi_int casadi_s1[3] = {5, 1, 1};
static const casadi_int casadi_s2[3] = {1, 1, 1};

static const casadi_real casadi_c0[3] = {0., 0., 1.};
static const casadi_real casadi_c1[9] = 
  {1., 0., 0., 0., 1., 0., 0., 0.,
  1.};

/* Drone_ode_mpcc_rate_mil_expl_ode_fun:(i0[14],i1[5],i2)->(o0[14]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, w00, *w01=w+4, *w02=w+7, *w03=w+10, *w04=w+19, w05, w06, w07, *w08=w+31, w09, w10;
  casadi_real *w11=w+37, w12, *w13=w+47, *w14=w+56, w15, w16, w17, w18, w19;
  const casadi_real *cr, *cs, *ct, *wr03;
  /* #0: @0 = input[0][3] */
  w00 = arg[0] ? arg[0][3] : 0;
  /* #1: output[0][0] = @0 */
  if (res[0]) res[0][0] = w00;
  /* #2: @0 = input[0][4] */
  w00 = arg[0] ? arg[0][4] : 0;
  /* #3: output[0][1] = @0 */
  if (res[0]) res[0][1] = w00;
  /* #4: @0 = input[0][5] */
  w00 = arg[0] ? arg[0][5] : 0;
  /* #5: output[0][2] = @0 */
  if (res[0]) res[0][2] = w00;
  /* #6: @0 = -9.81 */
  w00 = -9.8100000000000005e+00;
  /* #7: @1 = [0, 0, 1] */
  casadi_copy(casadi_c0, 3, w01);
  /* #8: @1 = (@0*@1) */
  for (i=0, rr=w01, cs=w01; i<3; ++i) (*rr++)  = (w00*(*cs++));
  /* #9: @2 = zeros(3x1) */
  casadi_clear(w02, 3);
  /* #10: @3 = 
  [[1, 0, 0], 
   [0, 1, 0], 
   [0, 0, 1]] */
  wr03 = casadi_c1;
  /* #11: @4 = zeros(3x3) */
  casadi_clear(w04, 9);
  /* #12: @0 = input[0][6] */
  w00 = arg[0] ? arg[0][6] : 0;
  /* #13: @5 = input[0][7] */
  w05 = arg[0] ? arg[0][7] : 0;
  /* #14: @6 = input[0][8] */
  w06 = arg[0] ? arg[0][8] : 0;
  /* #15: @7 = input[0][9] */
  w07 = arg[0] ? arg[0][9] : 0;
  /* #16: @8 = vertcat(@0, @5, @6, @7) */
  rr=w08;
  *rr++ = w00;
  *rr++ = w05;
  *rr++ = w06;
  *rr++ = w07;
  /* #17: @9 = ||@8||_F */
  w09 = casadi_norm_2(4, w08);
  /* #18: @8 = (@8/@9) */
  for (i=0, rr=w08; i<4; ++i) (*rr++) /= w09;
  /* #19: @9 = @8[3] */
  for (rr=(&w09), cs=w08+3; cs!=w08+4; cs+=1) *rr++ = *cs;
  /* #20: @10 = (-@9) */
  w10 = (- w09 );
  /* #21: @11 = @4; (@11[3] = @10) */
  casadi_copy(w04, 9, w11);
  for (rr=w11+3, cs=(&w10); rr!=w11+4; rr+=1) *rr = *cs++;
  /* #22: @10 = @8[2] */
  for (rr=(&w10), cs=w08+2; cs!=w08+3; cs+=1) *rr++ = *cs;
  /* #23: (@11[6] = @10) */
  for (rr=w11+6, cs=(&w10); rr!=w11+7; rr+=1) *rr = *cs++;
  /* #24: (@11[1] = @9) */
  for (rr=w11+1, cs=(&w09); rr!=w11+2; rr+=1) *rr = *cs++;
  /* #25: @9 = @8[1] */
  for (rr=(&w09), cs=w08+1; cs!=w08+2; cs+=1) *rr++ = *cs;
  /* #26: @12 = (-@9) */
  w12 = (- w09 );
  /* #27: (@11[7] = @12) */
  for (rr=w11+7, cs=(&w12); rr!=w11+8; rr+=1) *rr = *cs++;
  /* #28: @10 = (-@10) */
  w10 = (- w10 );
  /* #29: (@11[2] = @10) */
  for (rr=w11+2, cs=(&w10); rr!=w11+3; rr+=1) *rr = *cs++;
  /* #30: (@11[5] = @9) */
  for (rr=w11+5, cs=(&w09); rr!=w11+6; rr+=1) *rr = *cs++;
  /* #31: @13 = (2.*@11) */
  for (i=0, rr=w13, cs=w11; i<9; ++i) *rr++ = (2.* *cs++ );
  /* #32: @4 = mac(@13,@11,@4) */
  for (i=0, rr=w04; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w13+j, ct=w11+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #33: @3 = (@3+@4) */
  for (i=0, rr=w03, cr=wr03, cs=w04; i<9; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #34: @9 = @8[0] */
  for (rr=(&w09), cs=w08+0; cs!=w08+1; cs+=1) *rr++ = *cs;
  /* #35: @9 = (2.*@9) */
  w09 = (2.* w09 );
  /* #36: @11 = (@9*@11) */
  for (i=0, rr=w11, cs=w11; i<9; ++i) (*rr++)  = (w09*(*cs++));
  /* #37: @3 = (@3+@11) */
  for (i=0, rr=w03, cs=w11; i<9; ++i) (*rr++) += (*cs++);
  /* #38: @9 = 0 */
  w09 = 0.;
  /* #39: @10 = input[1][0] */
  w10 = arg[1] ? arg[1][0] : 0;
  /* #40: @14 = vertcat(@9, @9, @10) */
  rr=w14;
  *rr++ = w09;
  *rr++ = w09;
  *rr++ = w10;
  /* #41: @2 = mac(@3,@14,@2) */
  for (i=0, rr=w02; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w03+j, ct=w14+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #42: @1 = (@1+@2) */
  for (i=0, rr=w01, cs=w02; i<3; ++i) (*rr++) += (*cs++);
  /* #43: output[0][3] = @1 */
  if (res[0]) casadi_copy(w01, 3, res[0]+3);
  /* #44: @9 = 0.5 */
  w09 = 5.0000000000000000e-01;
  /* #45: @10 = input[0][10] */
  w10 = arg[0] ? arg[0][10] : 0;
  /* #46: @12 = (@5*@10) */
  w12  = (w05*w10);
  /* #47: @12 = (-@12) */
  w12 = (- w12 );
  /* #48: @15 = input[0][11] */
  w15 = arg[0] ? arg[0][11] : 0;
  /* #49: @16 = (@6*@15) */
  w16  = (w06*w15);
  /* #50: @12 = (@12-@16) */
  w12 -= w16;
  /* #51: @16 = input[0][12] */
  w16 = arg[0] ? arg[0][12] : 0;
  /* #52: @17 = (@7*@16) */
  w17  = (w07*w16);
  /* #53: @12 = (@12-@17) */
  w12 -= w17;
  /* #54: @17 = (@0*@10) */
  w17  = (w00*w10);
  /* #55: @18 = (@6*@16) */
  w18  = (w06*w16);
  /* #56: @17 = (@17+@18) */
  w17 += w18;
  /* #57: @18 = (@7*@15) */
  w18  = (w07*w15);
  /* #58: @17 = (@17-@18) */
  w17 -= w18;
  /* #59: @18 = (@0*@15) */
  w18  = (w00*w15);
  /* #60: @19 = (@5*@16) */
  w19  = (w05*w16);
  /* #61: @18 = (@18-@19) */
  w18 -= w19;
  /* #62: @7 = (@7*@10) */
  w07 *= w10;
  /* #63: @18 = (@18+@7) */
  w18 += w07;
  /* #64: @0 = (@0*@16) */
  w00 *= w16;
  /* #65: @5 = (@5*@15) */
  w05 *= w15;
  /* #66: @0 = (@0+@5) */
  w00 += w05;
  /* #67: @6 = (@6*@10) */
  w06 *= w10;
  /* #68: @0 = (@0-@6) */
  w00 -= w06;
  /* #69: @8 = vertcat(@12, @17, @18, @0) */
  rr=w08;
  *rr++ = w12;
  *rr++ = w17;
  *rr++ = w18;
  *rr++ = w00;
  /* #70: @8 = (@9*@8) */
  for (i=0, rr=w08, cs=w08; i<4; ++i) (*rr++)  = (w09*(*cs++));
  /* #71: output[0][4] = @8 */
  if (res[0]) casadi_copy(w08, 4, res[0]+6);
  /* #72: @9 = input[1][1] */
  w09 = arg[1] ? arg[1][1] : 0;
  /* #73: @12 = input[1][2] */
  w12 = arg[1] ? arg[1][2] : 0;
  /* #74: @17 = input[1][3] */
  w17 = arg[1] ? arg[1][3] : 0;
  /* #75: @1 = vertcat(@9, @12, @17) */
  rr=w01;
  *rr++ = w09;
  *rr++ = w12;
  *rr++ = w17;
  /* #76: @2 = vertcat(@10, @15, @16) */
  rr=w02;
  *rr++ = w10;
  *rr++ = w15;
  *rr++ = w16;
  /* #77: @1 = (@1-@2) */
  for (i=0, rr=w01, cs=w02; i<3; ++i) (*rr++) -= (*cs++);
  /* #78: @10 = 0.03 */
  w10 = 2.9999999999999999e-02;
  /* #79: @1 = (@1/@10) */
  for (i=0, rr=w01; i<3; ++i) (*rr++) /= w10;
  /* #80: output[0][5] = @1 */
  if (res[0]) casadi_copy(w01, 3, res[0]+10);
  /* #81: @10 = input[1][4] */
  w10 = arg[1] ? arg[1][4] : 0;
  /* #82: output[0][6] = @10 */
  if (res[0]) res[0][13] = w10;
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_mpcc_rate_mil_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Drone_ode_mpcc_rate_mil_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_mpcc_rate_mil_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_mpcc_rate_mil_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Drone_ode_mpcc_rate_mil_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Drone_ode_mpcc_rate_mil_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_mpcc_rate_mil_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void Drone_ode_mpcc_rate_mil_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_mpcc_rate_mil_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int Drone_ode_mpcc_rate_mil_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real Drone_ode_mpcc_rate_mil_expl_ode_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_mpcc_rate_mil_expl_ode_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Drone_ode_mpcc_rate_mil_expl_ode_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_mpcc_rate_mil_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Drone_ode_mpcc_rate_mil_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Drone_ode_mpcc_rate_mil_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 64;
  return 0;
}

CASADI_SYMBOL_EXPORT int Drone_ode_mpcc_rate_mil_expl_ode_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 64*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
